### ISSUE TITLE
SignalLogger maintains internal state so is not thread safe, even with per-thread Contexts

### ISSUE THREAD

**Issue by edrumwri** [RobotLocomotion/drake#10228]
Per discussion with @sherm1 the other day, SignalLogger is maintaining state (the log is mutable and maintained within the system). This violates our contract that Systems do not maintain state.

EDIT (sherm): the most serious consequence of this is that SignalLogger breaks thread safety even if a user is following the per-thread-Context rule. It should likely use the [MITLS](https://www.codeproject.com/Tips/875963/%2FTips%2F875963%2FMulti-Instance-Thread-Local-Storage) pattern as a cure.

SignalLogger also uses an O(n²) reallocation scheme that should be replaced with something better.

**Comment by jwnimmer-tri** [comment]
I disagree that this is a problem.  A system whose job it is to interact with code _outside_ of the simulation should feel free to keep local state, which is only exposed externally.  As long as the x, xdot, y, etc. calculations are not affected by the mutable member field, there is no issue.

**Comment by edrumwri** [comment]
I disagree with your disagreement. If we have the same system being used in multiple threads, race conditions will result. It's not hard to imagine that happening in this case. Safe parallelism will be straightforward to achieve if we keep the "code" and "data" segregated.

**Comment by jwnimmer-tri** [comment]
In general, nobody really has the right to assume that any given C++ class is intrinsically threadsafe.  That's not how code gets formulated by default.  Data races are usually guarded at a higher layer than any single object.

Beyond that, it is not currently a rule (and I don't think it should _be_ a rule) that every System must be implemented in a thread-safe way.  When you say "our contract that Systems do not maintain state", what do you mean?  I think we agree that the derivatives, discrete updates, outputs, etc. from a System should be deterministically based on the Context.  This issue seems to imply more than that, but I don't immediately see anywhere we've documented such restrictions.

**Comment by edrumwri** [comment]
It's a commonly expressed use case where people want to simulate (or otherwise evaluate) diagrams across multiple threads. While it might not be a rule that every System is implemented in a thread safe way, segregating the code and data is a straightforward way to facilitate that. If that wasn't the rationale for introducing the segregation, I don't know what was.

When you say that "derivatives, updates, outputs, etc. from a System should be deterministically based on the Context", you're pointing out that SignalLogger's log is state: there is no way to look at the (current) context and generate the log data.

**Comment by jwnimmer-tri** [comment]
You're right that there is sometimes an advantage to having a system be able to execute on multiple threads, and indeed many of our core systems should implement support for such.  But it should not be a _de jure_ restriction that _every single System_ must implement always.  My disagreement is with the implication that SignalLogger is _de-jure_ defective, rather than pointing out a use case where we need to acutely opt-in to being _de-facto_ thread-safe for this system.

In other words, is this a bug report or feature request?  I disagree that it's a bug report.  It could be OK as a feature request, but we'd need to see some evidence that we need the feature, before pursuing it.

> When you say that "derivatives, updates, outputs, etc. from a System should be deterministically based on the Context", you're pointing out that SignalLogger's log is state: there is no way to look at the (current) context and generate the log data.

I think you misunderstand me.  The `SignalLogger::data()` is **not** an output (in the System sense)!  It's just a method.  It doesn't need to be governed by the Context.  If it exposed the trajectory on an output port, _then_ the trajectory would need to be saved in the context.

> If that wasn't the rationale for introducing the segregation, I don't know what was.

Multithreading is absolutely _not_ the motivation for separating System from Context!

**Comment by edrumwri** [comment]
I'm standing by my assertion that this is defective. I really don't see how you can argue otherwise- this is a landmine waiting for a user to step on it.

**Comment by jwnimmer-tri** [comment]
Given that it's been this way since #4257 which is 2+ years old, I think the empirical risk of a user stepping on this is close to zero.  If it's such a significant hazard, why has nobody experienced a problem over its lifetime to date?

**Comment by edrumwri** [comment]
You want to collect statistics over a small N? And that argument might be useful in changing the priority of this issue, but it doesn't speak to whether this is a defect or not. 

I assert that this is a defect. There's no documentation about this potential problem, and multithreading is an already-employed use case. 

This line of argumentation does not seem consistent with your typical focus on defensive programming practices.

**Comment by jwnimmer-tri** [comment]
Oops.  I interpreted Evan's "the rationale for introducing the segregation" that he meant _only_ rationale.  Indeed, it is _one of_ the points in favor of System-vs-Context, but there are many more important ones.

**Comment by sherm1** [comment]
An easy and almost-compatible fix for this might be to provide an option for the user to provide SignalLogger a thread_local matrix in which to hold the log.

**Comment by sherm1** [comment]
The SignalLogger thread-safety problem is not fixed but is at least now documented in PR #10269. An additional problem is that it uses an O(n²) reallocation scheme. Both problems gain TODOs in #10269.

**Comment by jwnimmer-tri** [comment]
Per RobotLocomotion/styleguide#46, one resolution here would be to log into a scratch CacheEntry in the Context.  In that case all of the getters like `num_samples`, `data`, etc. would gain a `Context<T>` as an argument.

**Comment by jwnimmer-tri** [comment]
The code still has a TODO comment citing this issue that says SignalLogger is defective.  I think that's stale?

https://github.com/RobotLocomotion/drake/blob/3c4e32fc2aee7e3d8adeb8c74164d2690df38bc0/systems/primitives/signal_logger.h#L18-L19

**Comment by jwnimmer-tri** [comment]
Ugh, my bad.  I got mixed up about which file was old and which file was new.
