### ISSUE TITLE
Expose inboard_frame, outboard_frame in RevoluteJoint

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#10375]
Currently `RevoluteJoint` wraps ` RevoluteMobilizer`, but doesn't expose `RevoluteMobilizer`. There are some information in `RevoluteMobilizer` that can be useful. For example, the `inboard_frame()`, `outboard_frame()` function.

**Comment by EricCousineau-TRI** [comment]
I think you also wanted some proxy to some form of `CalcAcrossMobilizerTransform` as well?

FTR, this presently doesn't block work, as it can be hacked around by getting the internal tree and accessing the mobilizers there.

\cc @amcastro-tri @sherm1

**Comment by hongkai-dai** [comment]
> I think you also wanted some proxy to some form of CalcAcrossMobilizerTransform as well?

For my own project, I don't need this function `CalcAcrossMobilizerTransform`, but it would be nice to expose the function as well.

**Comment by amcastro-tri** [comment]
Joints only provide `Joint::frame_on_parent()` and `Joint::frame_on_child()`. However I believe @hongkai-dai what you want is not the physical graph information (Joint) but more like the model tree information (Mobilizer), since you used the inboard/outboard terminology. 
We are working with @sherm1 on providing this information in #10068. Once we finish that work you be able to ask any sort of tree information to a given MBP.

**Comment by hongkai-dai** [comment]
`RevoluteJoint` has `frame_on_child` and `frame_on_parent`.
