### ISSUE TITLE
Integrator statistics need to be adjusted when caching is enabled

### ISSUE THREAD

**Issue by edrumwri** [RobotLocomotion/drake#10992]
Integrators use a special derivative evaluation function to compute statistics over ODE calls. This function needs to be modified so that it understands when the derivative evaluation is cached and the ODE is not newly re-evaluated.

**Comment by sherm1** [comment]
FYI @edrumwri I determined experimentally that at least for the existing rk3 and implicit_euler test cases the Simulator never tries to evaluate the derivative twice with identical contexts.

**Comment by edrumwri** [comment]
Simulator never tries or the caching system never tries?

**Comment by sherm1** [comment]
Every call to `IntegratorBase::EvalTimeDerivatives()` done by the integrators caused an actual computation indicating either that (a) something in the context had changed since the last call, or (b) caching was not enabled. Looking at the tests it appeared that caching was manually enabled for almost all of them but I might have missed something. When #10979 lands (caching by default) we can retry but by inspection I couldn't actually spot a case where the integrators do repeated derivative calculations.

**Comment by edrumwri** [comment]
I'm missing something then because we're relying upon the caching system to keep from repeating the first-same-as-last computation: how could "every call ... [cause] an actual computation" and the "integrators [not] do repeated derivative calculations"?

**Comment by sherm1** [comment]
Which integrators actually compute derivatives after computing the final state value?

**Comment by edrumwri** [comment]
It depends how many steps you're taking. But regardless, there appears to still be a logical conflict in your statement above: either calls cause repeated computation or they don't (unless you're referring to a specific case, like existing tests, and not the general behavior).

**Comment by edrumwri** [comment]
Update per f2f: RK3 is not actually a FSAL integrator (contrary to its documentation).
