### ISSUE TITLE
Refactor RenderEngine test code

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#11965]
When testing RenderEngines, we have a suite of common tests: place a background plane, place a foreground shape, render, test values at particular pixels. For comparable rendering settings, all renderers should produce essentially the same image(s). 

Currently, across the three render engines (RenderEngine{Vtk|Ospray|Gl}) the common framework is not explicitly reflected in the code. One is very much a copy and paste of the other. The common RenderEngine tests should be refactored and expressed in terms of a generic render engine to maximize consistency and code re-use.

**Comment by huihuaTRI** [comment]
The naming of the internal variable `unordered_map<GeometryId, RigidTransformd> X_WV_;` has a conflict with Drake's monogram style. While it's arguable whether this is ok, I figure it worth marking it here for future discussion.

**Comment by SeanCurtis-TRI** [comment]
To refine that previous comment. See review discussion here: https://reviewable.io/reviews/robotlocomotion/drake/13583#-MAc9xbU4G_qAUYPbo6v

@huihuaTRI Can you describe the conceived conflict? It's not obvious to me, even with the reference to the conversation in the review.

**Comment by huihuaTRI** [comment]
Initially, when I read the member `X_WV_`, the first thought popped in my mind is that this represents some transformation. Then I realized that it has more information than just a transformation. Since you mentioned that you plan to refactor the code in the future, I figure it would be nice to add a comment here to remind this discussion for future reference, independent of whether we want to change the naming or not.

**Comment by SeanCurtis-TRI** [comment]
Sorry, I wasn't clear. I have no issue with you documenting an issue that came up during review that is relevant to this issue. I fully support that.

The problem is that I'm not clear on what is being documented. I see neither a clear statement of a problem, nor a clear statement of a resolution (this latter is not required, but always appreciated.  :D))  All I see is "conflict with Drake's monogram style". I don't understand what this "conflict" is. Can you be more explicit and detailed? What is the nature of the conflict?

**Comment by huihuaTRI** [comment]
Sure. The problem is that the naming of the definition `unordered_map<GeometryId, RigidTransformd>` has a similar pattern as what's been used by the drake transform monogram. It caused confusion initially. The reader (mainly me) thought it is a transform, but it actually contains more information. The proposition is that we could potentially use different naming for it during the refactor.

**Comment by SeanCurtis-TRI** [comment]
While I'm still not 100% sure of what your concern is, I think I have the idea. X_WV suggests a single transform, and the map contains a set of transforms. I feel your concern would be 100% resolved by changing the name `X_WV_` to `X_WVs_`. (Assuming frames W and V have some meaning). 

Certainly, this wouldn't cause concern:

`std::vector<RigidTransformd> X_WVs;`

So, similarly, this shouldn't either:

`std::unordered_map<GeometryId, RigidTransformd> X_WVs;`

They are both collections of transforms whose "key" value tells us something about interpreting the associated transform. In the first case, the keys are indices (which means we must now associate the index with something). In the second case, the key value is directly the `GeometryId` for the geometry we assume the pose applies.

**Comment by huihuaTRI** [comment]
Thanks, this is what I mean when I originally commented in the review process. Then you mentioned that the code will under refactor and this may be something you will consider in the refactor. I figure it might be worth adding a note here.

I was not strong about this change in the beginning since I realized that there are multiple similar cases in the code already. That being said, I am totally ok to keep it as it is.

**Comment by jwnimmer-tri** [comment]
@SeanCurtis-TRI -- I'm skeptical that keeping this open as a tracking issue has merit.  Shall we close it?

If in the course of changing our render engines to add new features we decide to refactor the tests, then we change the test code at that moment.  I don't see the point of refactoring test code unless and until we're changing the implementation code as well.

**Comment by SeanCurtis-TRI** [comment]
I think it's worth its own activity, but it's clear that this issue lacks the power to make that happen. Closing it is fine.
