### ISSUE TITLE
Failure at multibody/plant/multibody_plant.cc:1640 in CalcImplicitStribeckResults(): condition 'info == ImplicitStribeckSolverResult::kSuccess' failed.

### ISSUE THREAD

**Issue by 54WC** [RobotLocomotion/drake#12359]
Sometime, drake running fail due to bad parameter setting, the running is broke and come out a failure message on the bash terminal. like:Failure at multibody/plant/multibody_plant.cc:1640 in CalcImplicitStribeckResults(): condition 'info == ImplicitStribeckSolverResult::kSuccess' failed.

In case we running a parameter search, we often use for-loop to test a lot of conditions. 
Could we just skip the bad condition and test next condition rather than totally break the code running ?

**Comment by jwnimmer-tri** [comment]
\CC @amcastro-tri @edrumwri @sherm1

**Comment by edrumwri** [comment]
@54WC this means that the Simulator is not able to simulate the MultibodyPlant at this step size. Since this is an assertion, there's no way to catch the error (except trapping the signal, I suppose).

Some simple options are:
1.  Simulate at a smaller step size. There should be a sufficiently small step size at which point this failure won't occur (barring some NaN parameter settings).
2. Simulate using a continuous-mode MultibodyPlant (i.e., construct with a zero step size). The simulation will likely run more slowly, but this particular abort will no longer happen. 

@sherm1 it would be prudent for MBP to return a failure status in its discrete state update method (in place of the abort), which @54WC could then use to try simulating with a smaller step size.

**Comment by jwnimmer-tri** [comment]
As a workaround in the meantime, why not change the assertion to an exception?  Then, users (especially, pydrake users) could catch the exception and move on to the next scenario.

**Comment by 54WC** [comment]
> @54WC this means that the Simulator is not able to simulate the MultibodyPlant at this step size. Since this is an assertion, there's no way to catch the error (except trapping the signal, I suppose).
> 
> Some simple options are:
> 
> 1. Simulate at a smaller step size. There should be a sufficiently small step size at which point this failure won't occur (barring some NaN parameter settings).
> 2. Simulate using a continuous-mode MultibodyPlant (i.e., construct with a zero step size). The simulation will likely run more slowly, but this particular abort will no longer happen.
> 
> @sherm1 it would be prudent for MBP to return a failure status in its discrete state update method (in place of the abort), which @54WC could then use to try simulating with a smaller step size.

Thanks!  If there is a way to catch the error,  a " very bad reward" can be feedbacked to the action value in reinforce learning model.   Then the program will learn and go for another save way in the next episode.

**Comment by amcastro-tri** [comment]
As @edrumwri pointed out, this failure means the time step is too large for the given simulation conditions and causes the solver to diverge. The results are no longer valid and then we abort. I agree we could make this an exception @jwnimmer-tri.

**Comment by amcastro-tri** [comment]
See #12361. Also @54WC, I see you are running a version of Drake almost two month old (if not older).

**Comment by 54WC** [comment]
Yes, I start to run some code on Drake after  finishing Underactuated Robotic Spring 2019 course.  Actually, I followed Underactuated robotic course every year since 2015.  It is amazing but difficult for me. 
I expect I can build my underactuated robot someday at my slow pace.
