### ISSUE TITLE
MBP constructor should force users to pick discrete time or continuous time

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#12498]
After countless users have stumbled into unexpected errors because the default in MBP is continuous time, but continuous time can't handle many features like joint limits, @amcastro-tri suggested this solution.  Please make it happen?

Slack conversation: https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1555000606004800

**Comment by amcastro-tri** [comment]
Per Slack discussion, it looks like we prefer `MultibodyPlant(double discrete_update_period)` to not have a default value in order to force users to always provide a sensitive value and therefore hopefully prompt them to read the accompanying documentation.
Proper deprecation would be in order.

Please provide your thoughts here if you believe there'd be better options.

**Comment by amcastro-tri** [comment]
Note from @jwnimmer-tri: "Note that the parameter name time_step is part of the API, because it's bound in pydrake using that name.  I suggest not changing the name."

**Comment by amcastro-tri** [comment]
Addressed by #12525.

**Comment by RussTedrake** [comment]
The `AddMultibodyPlantSceneGraph` workflow, which is perhaps the more common one, still silently defaults `time_step` to zero.  
https://drake.mit.edu/doxygen_cxx/namespacedrake_1_1multibody.html#a184cfe8f301cf07076f5707501197d88

**Comment by jwnimmer-tri** [comment]
@amcastro-tri Are you working on the next PR here?  It would be nice to get it into the next tag, which is predicted to be early next week.

**Comment by amcastro-tri** [comment]
per f2f with @jwnimmer-tri. We'll:
1. Provide an overloads taking `time_step` for when the plant is not provided.
2. Require a valid plant pointer for the signature taking a plant.
