### ISSUE TITLE
pydrake doc: Class constructors (__init__) have weird ordering?

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#12604]
EDIT(eric): Re-scoping to just `__init__` ordering

---

Related to #11954.

I've noticed that the documentation for the class and the constructor of ManipulationStation is missing:
https://drake.mit.edu/pydrake/pydrake.examples.manipulation_station.html?highlight=manipulationstation#pydrake.examples.manipulation_station.ManipulationStation

By contrast, the Adder system looks good:
https://drake.mit.edu/pydrake/pydrake.systems.primitives.html?highlight=adder#pydrake.systems.primitives.Adder_

Is this inconsistency still expected, given that #11954 is closed?

**Comment by EricCousineau-TRI** [comment]
It doesn't seem expected; the docstring seems like it should be there:
https://github.com/RobotLocomotion/drake/blob/489048bd4fae938df4cbb850d6dff04522b86101/bindings/pydrake/examples/manipulation_station_py.cc#L40-L41

\cc @jamiesnape

**Comment by m-chaturvedi** [comment]
-  > I've noticed that the documentation for the class and the constructor of ManipulationStation is missing:

   We might have missed it because it's not at its usual place:
   http://bit.ly/2Un1rMI
   [ Converted to bitly because it looks like there's a markdown bug for hyperlinks with trailing underscores : https://github.com/markdown-it/markdown-it/issues/38 ]

-  Why is this happening?

    It looks like in Python's `sorted` function which is used to sort the doc members alphabetically,  capital letters are favored over underscores:
    https://repl.it/repls/BusyEmbellishedPostscript 
    https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/autodoc/__init__.py#L501-L506
    (Ubuntu's Sphinx 1.6.7 has a similar `__init__` file that I'd tested with)   

-  How to 'fix' it?

   One way that I've tried, could be:  https://github.com/m-chaturvedi/sphinx/commit/45476ed5cfd056b26deac25d7c03430db72ca1ab

**Comment by RussTedrake** [comment]
Thank you. What about the class documentation?

https://drake.mit.edu/doxygen_cxx/classdrake_1_1examples_1_1manipulation__station_1_1_manipulation_station.html

**Comment by m-chaturvedi** [comment]
It looks like we missed the docstrings for them (#12675).

**Comment by EricCousineau-TRI** [comment]
Regarding member order: Hm... I'm really hesitant about forking `sphinx` code; would almost prefer monkey patching over that.

That being said, it looks like all classes have their `__init__` members placed in the same order.

Looks like there are options to control the ordering, e.g.:
https://stackoverflow.com/a/58996596/7829525
Perhaps there's a way to intercept that with a handler / monkey patch instead.

**Comment by m-chaturvedi** [comment]
> Regarding member order: Hm... I'm really hesitant about forking sphinx code; would almost prefer monkey patching over that.

I was meaning to create an issue and seeing if they accept the issue / PR.  Maybe that wouldn't solve our problem because we're using an Ubuntu package.  

I had tried the `bysource` option in `config.py`, but it had not solved our problem.

Another way could be to more consistently name our methods.  Please correct me if I'm wrong, but I guess our (regular) python code style doesn't accommodate method/functions starting with a capital letter.  Maybe we should not care about the C++ style in our bindings' code and make it consistent with regular python code by making those function names snake_case.

**Comment by jamiesnape** [comment]
> Another way could be to more consistently name our methods. Please correct me if I'm wrong, but I guess our (regular) python code style doesn't accommodate method/functions starting with a capital letter. Maybe we should not care about the C++ style in our bindings' code and make it consistent with regular python code by making those function names snake_case.

I would probably go the opposite way and change pure Python public methods into non-snake-case (any other Python in Drake follows normal naming conventions, however), but honestly, we should not rename anything while we are working out generating the bindings.

**Comment by jwnimmer-tri** [comment]
I don't think anyone is complaining about the order of CamelCase vs snake_case methods.  The only complaint is that `__init__` should be at the top, yes?

**Comment by EricCousineau-TRI** [comment]
That's my complaint (and I believe Russ's). I do not believe we should change any of the conventions used in the Python bindings.

**Comment by EricCousineau-TRI** [comment]
Per f2f, this might be happening because of the issue in https://github.com/RobotLocomotion/drake/issues/11954: B/c `pybind` does not produce a full name that includes the class name, we then introduced a workaround to always put `__init__` in, but then we may affect the sorting order because of this.

Ideally, we just find a way to plugin to change the sorting order.

**Comment by RussTedrake** [comment]
Yes, `__init__` at the top was my primary ask (beyond the missing class documentation which was already resolved).

**Comment by m-chaturvedi** [comment]
I'd asked it on the group: https://groups.google.com/forum/m/#!msg/sphinx-users/bSAWjiiDWik/BlRNSMQoFgAJ

**Comment by EricCousineau-TRI** [comment]
In the Group post, I think it'd be important to mention the lines you alluded to - where we provide an explicit exception for `__init__` capsules:
https://github.com/RobotLocomotion/drake/pull/12452/files

If we hadn't needed that exception, I'd assume everything would be fine.

**Comment by m-chaturvedi** [comment]
Sorry for the late response. 

> Per f2f, this might be happening because of the issue in #11954:

No, I am not sure about this.

>In the Group post, I think it'd be important to mention the lines you alluded to.

I am not sure about this either.

I think the two problems are disparate, at least at the outset.  I can demonstrate my claim with the following (tested using `tox -e py36 tests/test_autodoc.py`):
https://github.com/sphinx-doc/sphinx/compare/master...m-chaturvedi:test_member_order?expand=1

I maintain that the cause is: `assert sorted(["a", "__init__", "A"]) == ["A", "__init__", "a"]`.

**Comment by EricCousineau-TRI** [comment]
Yup, that looks like pretty solid proof that it's just sorting. Thanks for posting it!

**Comment by EricCousineau-TRI** [comment]
As Mmanu showed, `bysource` does the correct thing for Python code, but it's unclear if this will work for Python C extensions.

**Comment by m-chaturvedi** [comment]
IIRC, the code analyzer which doesn't seem to work for us:
https://github.com/sphinx-doc/sphinx/blob/af62fa61e6cbd88d0798963211e73e5ba0d55e6d/sphinx/ext/autodoc/__init__.py#L674

`self.analyzer` is `None` when `bysource` is used for our code.

There have been other complaints regarding `bysource` not working properly:
https://github.com/sphinx-doc/sphinx/issues/3673

**Comment by EricCousineau-TRI** [comment]
Re-opening; see #12910 for details.
