### ISSUE TITLE
BotVisualizer constructor should properly clear existing drake designer

### ISSUE THREAD

**Issue by tkoolen** [RobotLocomotion/drake#1307]
Currently if you run e.g. the unit tests in systems/plants/test, the visualizer will not erase some objects from tests that have already finished, e.g. these blue dots:

![image](https://cloud.githubusercontent.com/assets/2585880/9588742/e783e3aa-4ff7-11e5-9ef8-5178ce9f1dce.png)

Is there a simple 'clear' message we could send in the constructor of BotVisualizer if a previous viewer was found?

**Comment by patmarion** [comment]
Is it possible that those blue dots are from lcm-gl messages and not drake draw messages?

**Comment by RussTedrake** [comment]
i would definitely suspect they are from lcmgl.  @tkoolen -- please let us know so we can act on it with @patmarion 's help this week if necessary.

**Comment by jwnimmer-tri** [comment]
So the general problem here may still exist, but this particular realization of it is no longer relevant, both because these tests won't exist soon, and because lcmgl is not used very much within Drake anymore.

Closing as won't-fix, because #6369 will be removing the relevant software.

If I'm confused and this should in fact stay open, please re-open an clarify the remaining unsolved problem(s) in a new comment here.
