### ISSUE TITLE
drake_visualizer: Should fix the weird round-off error artifacts for ground planes

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#13828]
When running `drake-visualizer`, it seems like there's some round-off error between parallel + intersecting faces (e.g. a ground plane and the `grid` objects plane).

Example:

```
$ git log -n 1 --oneline --no-decorate
ade13ca064 Add bindings for PlanarJoint (#13813)
$ bazel run //tools:drake_visualizer &
$ bazel run //examples/atlas:atlas_run_dynamics -- --simulation_time=0.
```

Screen cap:
> ![image](https://user-images.githubusercontent.com/26719449/89479028-c1b5bf00-d75f-11ea-93de-11e9fbdaed2e.png)

FYI @SeanCurtis-TRI @jamiesnape

**Comment by EricCousineau-TRI** [comment]
Setting the grid to be wireframe-only fixes the artifact (for ground planes, that is):

> ![image](https://user-images.githubusercontent.com/26719449/89479140-0a6d7800-d760-11ea-8460-8a85301f1008.png)

**Comment by SeanCurtis-TRI** [comment]
FTR *technically* changing to wireframe mode doesn't "fix" the artifact, it merely reduces the artifact by orders of magnitude. What you have going on here is [z-fighting](https://en.wikipedia.org/wiki/Z-fighting). As you rotate the camera you can still get flickering on the lines, but since it is a *much* smaller fraction of the rendered pixels it will be less "in-your-face" obnoxious.

That said, I'm fully in favor of simply changing the surface mode by default as actually having a semi-transparent ground plane provides limited value. 

As I see it, there are two paths forward:

1. Change `director` and update `drake`'s build resources to use it. This would require kitware time.
2. Akin to the hack for [fixing the infinite bounding box](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/limit_clipping_range.py), we can add a start up script on the Drake side that toggles it. There are two questions for me on whether this option would work:
    - Would this get reset every time a new scene is loaded?
    - If there is a per-scene reset, is there a callback interface for toggling it again *after* the scene has been loaded?

**Comment by SeanCurtis-TRI** [comment]
And *then* I realized that you'd already created a PR.  :-/

**Comment by EricCousineau-TRI** [comment]
:grimacing: 

Yeah, went for (2). Nothing special required!

**Comment by jamiesnape** [comment]
I am looking to rebuild Director probably next month when I upgrade VTK, so if also wanted to send something to Director, we could pick it up in the not too distant future. Not the first z-fighting issue we have seen.

**Comment by SeanCurtis-TRI** [comment]
I like the idea of not having plug-in architecture to do something so simple.

Looking in director it appears that [the `GridItem` defaults to being wireframe](https://github.com/RobotLocomotion/director/blob/master/src/python/director/visualization.py#L1018) but the 
[main window app sets it to "surface with edges"](https://github.com/RobotLocomotion/director/blob/master/src/python/director/mainwindowapp.py#L185). Seems like a relatively *tiny* change in director. We simply remove that one line and we're done.

We've carried this cost for years. If we can resolve it so simply in the next month, I'd say it's worth waiting the one month.

**Comment by EricCousineau-TRI** [comment]
I am totally down for fixing this in a more principled fashion in the future.

However, I disagree with waiting another month.
The PR is *small* and should merge today: ![image](https://user-images.githubusercontent.com/26719449/89562149-8a8af080-d7e7-11ea-8c91-9233e0668313.png)

Let's just merge it now, then fix it later?

**Comment by SeanCurtis-TRI** [comment]
@jamiesnape Shall I open a new task for us to track the `director`-side change to make sure it's properly on kitware's radar?

**Comment by EricCousineau-TRI** [comment]
I'm also cool with re-opening this - I think that pretty much has all the info here?
