### ISSUE TITLE
common: Should define clear convention on how to handle paths

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#14212]
Namely, should directories always end with slashes, or never. It should never be "in between".

Example: `PackageMap::GetPath()` should either always have a trailing slash, or never. Period.
It should either fail if `Add()` is called poorly, or it should strip it.

See:
https://github.com/robotlocomotion/drake/pull/14211#pullrequestreview-508375268

> minor: These trailing-slash-handling lines are a bit confusing after lexical normalization. It would be good to cite https://cplusplus.github.io/LWG/issue3096 here for the proposition that trailing slash handling in lexical normalization is an area of active churn in standards interpretation and cannot be relied on one way or the other.

FYI @ggould-tri

**Comment by jwnimmer-tri** [comment]
I don't necessarily disagree, but:

(1) Do we need a tracking issue for this, given that nobody is ever going to work on it?

(2) Once [std::filesystem](https://en.cppreference.com/w/cpp/filesystem) support is added by Apple Clang, we should just change all of our std::string paths to fs::path paths, and then the problem is resolved.

Given that, should we close this issue?

**Comment by EricCousineau-TRI** [comment]
Yup, SGTM!
