### ISSUE TITLE
Added j2s6s300_sphere_collision.urdf

### ISSUE THREAD

**Issue by mpatalberta** [RobotLocomotion/drake#14565]
Though the arm look correct the simulator does not output the correct result.
I had found that jaco_controller,jaco_simulator move had to be changed to read the j2s6s300_sphere_collision.urdf where changed as default
The jaco_constants.h needed to be changed to 6 joint from 7.

Still the output from the simulator looked in correct.
Could some one please look or suggest what is  going wrong here.

**Comment by SeanCurtis-TRI** [comment]
@mpatalberta It seems that you're creating new issues instead of continuing the discussion in #14556. Is that intentional? This seems to be a continuation of that conversation.

I'm closing this for now and would suggest you put your response into that PR. If I'm mistaken, you can clarify this issue and re-open it.
