### ISSUE TITLE
Bug with hydroelastic visualization

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#14578]
For details refer to the internal TRI [Slack conversation here](https://tri-internal.slack.com/archives/C2BMF3K28/p1611676244032300).

We observed that in hydroelastic simulations leading to multiple contact patches, one of the patches seems to include all other patches, therefore repeating the information. More precisely, in all tests it seems it is the last patch in the `Hydroelastic Contact` panel in Drake viz that seems to show this problem.
We verified that the data in `ContactResults` (produced by `MBP::CalcContactResultsContinuousHydroelastic()`) and in `lcmt_contact_results_for_viz` (produced by `ContactResultsToLcmSystem::CalcLcmContactOutput()`) is correct and does not show this duplication (see [commit used to verify this here](https://github.com/amcastro-tri/drake/commit/ce5466ddc81f263c044ea803869c0a23c0f7a149)).

Therefore we believe this issue is purely related to visualization and does not affect the dynamics of the system.

**Comment by SeanCurtis-TRI** [comment]
TODO: Create scenario to reproduce the issue (e.g., create a unit test. :D)

**Comment by xuchenhan-tri** [comment]
The root cause of the issue seems to be the DebugData variable being defined outside of the loop for contact surfaces. See [here](https://github.com/RobotLocomotion/drake/blob/9a1b66f351b470bad0a6f4827eb8069dfab48dda/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L635) for the source.

There has been a few changes to hydroelastic visualization since this issue was filed. In particular, #14622 alleviates the issue to some degree by passing the pressure field data directly to VTK instead of through DebugData. So the issue described can't seem to be completely reproduced. The contact forces and moments, however, are still being visualized through DebugData and the bug still persists. 

The fix should be easy (moving the definition of the DebugData to inside the loop). I'm working on stripping down my reproducing case to a minimal unit test and I'll make a PR for a fix soon.

**Comment by amcastro-tri** [comment]
nice! thanks @xuchenhan-tri!
