### ISSUE TITLE
mbp: Should ensure "world" is an implicitly named body/frame

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#14638]
Per https://github.com/RobotLocomotion/drake/pull/10055#issuecomment-777847377, it can be painful to realize that `"world"` may not explicitly exist in MBP, as it's used as an explicit interface element in specs like URDF and SDFormat (e.g. the parent body of a joint). (See parsing code, where it says stuff like `if name == "world": return plant.world_body()`).

At present, the world body/frame are accessible through things like `MultibodyPlant.world_frame()`, `MultibodyPlant.world_body()`, the named instance of `"WorldBody"`, and the relevant geometry info through `SceneGraph::world_frame_id()`.

Options:

1. Register an alias, but keep both around forever :shrug: 
   - The body itself is still named `WorldBody`, so listing bodies/frames by name will contain `WorldBody`, but not `world`
2. Rename `WorldBody` to `world`, keep `WorldBody` as an alias that triggers a runtime deprecation.
   - The body itself is now named `world`, so listing bodies/frames by name will contain `world`, but not `WorldBody`
3. Allow users to specify a "default world name", so that it matches whatever parsing utility or code convention they are using.
4. (As of 2022-10-21) Just rename it to `world`

\cc @naveenoid @amcastro-tri

**Comment by amcastro-tri** [comment]
This problem could keep happening if we ever decide to support other file formats with other naming conventions.
IMO, it'd be best if the name for the "world" (as for any other body) matches whatever name that file format specifies.
Therefore a third option would be:
3. Allow users to specify a "default world name", so that it matches whatever parsing utility or code convention they are using.

And along with that, since we do mostly support URDF and SDF, make our Drake convention to match those. i.e. do the renaming WorldBody --> body and deprecate the former.

**Comment by EricCousineau-TRI** [comment]
Sounds good to me.

I'm a bit leery of (3), TBH, but I've added it to the summary above.
