### ISSUE TITLE
Add human-readable output stream operators for RollPitchYaw, RotationMatrix, RigidTransform objects

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#14699]
Per @ggould-tri's request in [this Slack discussion](https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1614099389009600) it would be convenient to have `operator<<()` available for these classes so that Drake users don't have to repeatedly create their own debugging and logging stringifiers for these hard-to-interpret classes.

Per the discussion there, these would be solely for the convenience of human observers. It is already easy to output the matrix form of these objects, since they already provide for conversion to suitable Eigen objects, and those do support `operator<<()`. As Grant points out, nearly all rotation _inputs_ to Drake (provided by humans) are in the form of roll/pitch/yaw angles. Hence the most natural output is in the same format.

Here is a strawman proposal that attempts to balance clarity and brevity for human consumption:
- `operator<<(ostream, RollPitchYawd)`
    writes "rpy=_r_ _p_ _y_" where the italics is replaced by angles in radians (does not write out the units). No extra spaces, no terminating newline.
- `operator<<(ostream, RotationMatrixd R)` is just `ostream << RollPitchYawd(R);`
- `operator<<(ostream, RigidTransformd X)` writes "rpy=_r_ _p_ _y_ xyz=_x_ _y_ _z_"

Ideally these would work for scalar types T other than T=double, but I'm guessing there is much less need for that -- thoughts?

**Comment by mitiguy** [comment]
Opened PR# 14910 to address issue #14699.

**Comment by mitiguy** [comment]
This issue is being closed as:
operator<<(ostream, RollPitchYaw) was addressed in PR [#14910](https://github.com/RobotLocomotion/drake/pull/14910).
operator<<(ostream, RigidTransformd X) was addressed in PR [#14910](https://github.com/RobotLocomotion/drake/pull/14910).

operator<<(ostream, RotationMatrixd R) as just ostream << RollPitchYawd(R); was not addressed.
It was not addressed since it is easily implemented by the user. 
 If desired (e.g., @ggould-tri or @sherm1 to let us know if this is used often), this issue can be reopened and I can fix it.
