### ISSUE TITLE
Some build servers are down?

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#1496]
It looks like for the last week, we've only been getting test results back from drake001 and drake006 on all the pull requests. drake003 and drake004 haven't commented on anything since ~7 days ago.

**Comment by RussTedrake** [comment]
Just manually rebooted them.


On December 4, 2015 at 5:33:17 PM, Robin Deits (notifications@github.com) wrote:

It looks like for the last week, we've only been getting test results back from drake001 and drake006 on all the pull requests. drake003 and drake004 haven't commented on anything since ~7 days ago.
