### ISSUE TITLE
Make `drake::copyable_unique_ptr` const-correct

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#15344]
Per a discussion on slack.  @jwnimmer-tri originally said "The `std::unique_ptr` has const-get that returns mutable-pointer, but `drake::copyable_unique_ptr` diverges from that pattern and stays const-correct."  But upon inspection:
```
copyable_unique_ptr<ConvexSet> c = std::make_unique<MutablePoint>(Vector2d{1., 2.});
const copyable_unique_ptr<ConvexSet>& c_ref = c;
static_assert(std::is_const_v<decltype(*c_ref)>);
```
fails the static assert.  To which Jeremy responded "Eww, I missed that `copyable_unique_ptr` inherits from `std::unique_ptr<T>` and fails to shadow `operator*` to preserve const-correctness.  We should look into fixing this..."

This would improve my use of `copyable_unique_ptr` in `ConvexSets`.

**Comment by jwnimmer-tri** [comment]
@SeanCurtis-TRI and @sherm1 could you weigh in here on whether the _intention_ of `copyable_unique_ptr` was to have `operator*` propagate the const, like we have `.get()` vs `.get_mutable()` in its API?

And if that answer is "yes", could I convince one of you to take the issue and push forward on a fix?

**Comment by RussTedrake** [comment]
Can we also add 
```
  explicit copyable_unique_ptr(T& ref) noexcept
      : std::unique_ptr<T>(ref.Clone()) {}
```
?? That makes constructing lists of `copyable_unique_ptr` much nicer.

**Comment by RussTedrake** [comment]
I've opened #15345 if you care to see my specific use case.

**Comment by SeanCurtis-TRI** [comment]
I'll take a look.

As to adding a `noexcept` on the constructor...I'd imagine that it transitively requires `noexcept` on `T::Clone()` as well, right?

**Comment by RussTedrake** [comment]
I wasn't trying to make a statement about `noexcept`.  That part, I'm afraid, was just copy-pasta from the constructor above.  I figured you would make it perfect.

**Comment by SeanCurtis-TRI** [comment]
Ah, you'd just like to copy it from a reference.  :)  Whether it's `noexcept` or not is not something you care about.  Got it.

**Comment by SeanCurtis-TRI** [comment]
So, I'm convinced that distinguishing between `operator*()` and `operator*() const` is a good thing. Technically, the distinction has nothing to do with the concept of a copyable `unique_ptr`. The reason we added the distinction between `get()` and `get_mutable()` was so that we could swap `copyable_unique_ptr` with an eventual `copy_on_write_ptr` in the future. And by introducing the mutable-non-mutable distinction now, it would inherently do good things after the swap without extensive reasoning. In that spirit, the fact that `unique_ptr::operator*() const` happily returns a non-const reference (like `unique_ptr::get() const` returning a non-const pointer) means that it needs equal treatment.

**Comment by jwnimmer-tri** [comment]
The short-term fix can be shadowing the operator, so that _most_ code will behave as we want.

However, even with that, the user can still upcast to unique_ptr (and indeed, sometimes that will happen automatically) and drop the propagated const.  I believe the longer-term fix must be to replace the public inheritance with a conversion operator to unique_ptr instead.  That should fully seal the abstraction.

**Comment by SeanCurtis-TRI** [comment]
I've submitted the PR with the short-term fix. I'm waiting to see how CI goes. There might be some usage somewhere where a `const copyable_unique_ptr` is having its value mutated. CI will let me know.

> ... conversion operator to unique_ptr instead

And, presumably, the conversion would itself create a copy so that the `unique_ptr` (with all of its `const` wackiness) would own its own copy as is right and proper. "Convert" in that context feels like the wrong term. And possibly redundant. Here's how I see it:

```c++
copyable_unique_ptr<Foo> my_foo = make_unique<Foo>(param1, param2);
// If I know T is copy constructible
unique_ptr<Foo> foo_copy = make_unique<Foo>(*my_foo);
// If I know T clones.
unique_ptr<Foo> foo_copy2 = my_foo->Clone();
// If we have the "conversion" method.
unique_ptr<Foo> foo_copy3 = my_foo.make_unique();
```

So, the *real* value of a method (e.g., `unique_ptr<T> make_unique() const`) would be to mask the copying mechanism of `T`.

**Comment by jwnimmer-tri** [comment]
I say "convert" only because its the term of art https://en.cppreference.com/w/cpp/language/cast_operator.

I suspect that the conversion operator could be overloaded on the value category of `*this` to avoid a copy/clone.
