### ISSUE TITLE
py mp: Binding_{Evaluator} should really be Binding[Evaluator]

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#15406]
Been meaning to fix this.

Currently, we have things like `Binding_LinearCost` which was a holdout before the following code got introduced (#7757).
Will be easy to swap it out.

\cc @hongkai-dai @RussTedrake

**Comment by RussTedrake** [comment]
I'm just about to start using this often (I've chosen to accept only the Binding variant of AddCost in my GraphOfConvexSets, instead of the way MathematicalProgram basically replicates all of the Binding constructors in it's public API.  

Since we haven't actually bound the constructor for Binding_foo in pybind yet, I think you could make this change now withtout deprecation(?), but I'm about to start having code that constructs Binding_foo objects hopefully in the next day or two!

**Comment by EricCousineau-TRI** [comment]
I think I understand - make the change, then add the deprecation?

**Comment by EricCousineau-TRI** [comment]
But that being said, would it be too hard to account for the deprecations and use the spelling?
