### ISSUE TITLE
Bring in libcmaes as a dependency

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#16433]
Now that [libcmaes](https://github.com/CMA-ES/libcmaes) has the Apache 2.0 license, I think it is ready to bring it as a Drake dependency

**Comment by jwnimmer-tri** [comment]
@hongkai-dai will provide a small sample function (or program, or test) that calls cmaas, and then @jwnimmer-tri will open a PR with a sufficient BUILD file (+ releated) to get that working in Drake.

**Comment by jwnimmer-tri** [comment]
A good sample program to use would be https://github.com/CMA-ES/libcmaes/blob/master/examples/sample-code.cc.

**Comment by jwnimmer-tri** [comment]
@hongkai-dai for tracking purposes, could you document in this issue which Drake feature this dependency will be in service of?  Ideally, that new feature would have its own overall Drake tracking issue that you could just link to here.

**Comment by jwnimmer-tri** [comment]
@hongkai-dai Do we have any timeline for using this CMA-ES library in Drake?  We added it 18 months ago as a speculative dependency ("dev" code) and haven't touched it since then (other than babysitting it to keep it up-to-date).

Now that #17231 is nearing completion, I either need to fix the CMA-ES to be hidden-safe or else remove it from Drake.  (We could bring it back later again if we want to, reverting the removal.)

**Comment by hongkai-dai** [comment]
I ended up not using CMA-ES. I think we can close this issue.
