### ISSUE TITLE
APT release improvements

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#16448]
Our release process for APT is somewhat obscure and undocumented, uses a fork of drake at https://github.com/RobotLocomotion/debian-drake that must be manually maintained, and compiles Drake from scratch using different build flags but doesn't run the tests.

Overall, this is all way more complicated than we need, and adds friction to the release process.

We should explore using something more akin to `alien` to create the `*.deb` files for our apt site, where we simply take the existing `*.tar.gz` that's already built and tested and shipped everywhere, and add the correct `debian/control` meta-data (and possibly re-organize the files to match Debian layout).

- [X] Initial implementation for `.tgz` => `.deb` via `alien` (#16602)
- [x] Polish up `repack_deb` to fix permissions and installation dependencies (#17058)

**Comment by jwnimmer-tri** [comment]
Given the recurring glitches with apt builds, I've upgraded this to "high" priority.

I've filed #16602 with a first draft of the revised deb-making script.  It's not ready to take over production releases yet, but it should provide a solid starting point.

**Comment by jwnimmer-tri** [comment]
For clarity -- as part of this transition, we will no longer ship the `drake-doc` package.

**Comment by svenevs** [comment]
Inlining https://github.com/RobotLocomotion/drake/issues/12783#issuecomment-672266985 as a checklist for revision:

- [ ] Ensure vtk explicitly links to all its dependencies.
    - VTK 9 is good to go.
    - [ ] VTK 8 is going to use the current rpath patching, to be removed when drake-visualizer is dropped.
- [ ] Fix file permissions for non-executables.
- [ ] Install models licenses into share/doc.
- [ ] Move binaries from share/drake to lib/drake.
- [ ] Patch director to remove shebangs from non-executable third-party Python files.
- [ ] Remove cruft from doxygen (*.map, *.md5, doxygen.log), sphinx (.buildinfo), empty jars (drake-lcm-spy.jar, lcm-logplayer-gui.jar, lcm-spy.jar), Bazel launcher scripts (cart_pole_passive_simulation, pendulum_lqr_monte_carlo_analysis, run_planar_scenegraph_visualizer), and add tests to keep everything clean.
    - Some of these are irrelevant since we are skipping docs.
- [ ] Remove unused headers (ibex/, maybe vtk/) and any unused CMake configuration.
- [ ] Strip .comment and .buildinfo sections from binaries.
- [ ] Use correct file extension for Python C/C++ extensions (e.g., .cpython-36m-x86_64-linux-gnu.so, etc.) and install to lib/python3/{dist-packages or site-packages}.

It seems like for a number of these, it would be advantageous to fix the drake install logic rather than doing a post-processing step.  For example, if I just omit these three lines

https://github.com/RobotLocomotion/drake/blob/902c14f83cba382b309b779f2dd5d031ce3304bf/tools/workspace/ibex/package.BUILD.bazel#L389-L391

then removing `include/ibex` is not necessary.  Is there any reason to keep it as a post-processing step rather than just removing it from the install logic?

Making any progress on these while the release tooling is in development (and thus the debian-drake repo is still being used) may result in potential breakages but at least for the cleanup ones [`rm -rf` is used](https://github.com/RobotLocomotion/debian-drake/blob/9ed94326b5811cd82a45bddce360cf2fbf899828/debian/rules#L51) which will not fail if it is not found.  Let me know your thoughts on fixing in drake vs doing post-processing.

**Comment by jwnimmer-tri** [comment]
Most of the post-processing is wrong anyway.  We should keep things as-if the user did something like `cd /opt && sudo tar xfz drake-yyyymmdd.tar.gz`.  In other words, don't change the install paths at all, just because of the different release channel.

This will change the file layout in the apt package, compared to what users were used to.  That's fine, we'll announce it as a breaking change.

For thing like fixing the file permissions, yes we should do that as part of the main installer logic, so that even the tarballs are fixed.

**Comment by jwnimmer-tri** [comment]
For (7), we are shipping IBEX and VTK as public shared libraries, so we should continue to install their headers so that users can build & link against those libraries while also linking to Drake.

**Comment by jwnimmer-tri** [comment]
FYI from meeting today -- the goal would be to run this in CI as part of a Packaging build, where the build first creates the release tarball (as it does now) and then also re-packs that into a `*.deb` file.

**Comment by svenevs** [comment]
I have some stuff up in #17058, I need to come back tomorrow and undo those changes to get the original list of warnings -- some of them seem possible to fix in drake itself.  For example, it looks like generated header files in `gen/` folders were getting their executable bits set?  Right now that approach is a bit brute-force...

**Comment by jwnimmer-tri** [comment]
It might make sense to split a new `component: continuous integration` issue for "Run deb repacker during Nightly Packaging, push to S3" and then close this one?  We will probably want to defer that work until after the tool is moved out of `dev` folder?

**Comment by svenevs** [comment]
=> https://github.com/RobotLocomotion/drake/issues/17177
