### ISSUE TITLE
The default "point" contact model currently ignores hydroelastics

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#16565]
Per Slack thread [here](https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1644462635505389?thread_ts=1644437000.738829&cid=C2WBPQDB7) a user was understandably surprised that after properly annotating geometry with hydroelastic properties his simulation used only point contact.

Changing the default contact model from Point to HydroelasticWithFallback would eliminate that surprise but still use point contact for un-annotated geometry.

If we make this change we should update the hydroelastic user guide also to reflect it.

My proposal would be to change it now for Drake 1.0. Assigned to Rico initially for delegation/disposition.

**Comment by joemasterjohn** [comment]
I would say that it is most definitely a breaking change. If a user had a model with `<drake:compliant_hydroelastic/>` defined yet used the default point contact mode (purposefully or inadvertently) would see big changes in their simulation.

**Comment by jwnimmer-tri** [comment]
We should definitely announce it carefully, because it might impact users, but recall that anything to do with hydroelastics is categorized as "experimental" and is subject to breaking changes without a deprecation period.  If we think the new default is better, we should land it, with suitable announcement text.

**Comment by rpoyner-tri** [comment]
@DamrongGuoy agreed to evaluate the change over drake and anzu, and help understand the impact.

**Comment by DamrongGuoy** [comment]
@sherm1 @rpoyner-tri   
As the assignee of this issue, I tested the Draft PR #16569.  It already triggered 69 unit test failures (out of 788) in `multibody`.  I guess it won't be trivial to switch.

```
damrongguoy@P52-DGuoy:~/GitHub/DamrongGuoy/drake (default_HydrolasticWithFallback)$ bazel test //multibody/...
...
Executed 788 out of 788 tests: 719 tests pass and 69 fail locally.
INFO: Build completed, 69 tests FAILED, 1270 total actions
```

CC: @amcastro-tri

**Comment by DamrongGuoy** [comment]
I agree that a few lines of change in `multibody` could have a significant impact on the user's code.  I'm testing Anzu-master-Drake-PR now.  I wonder what I should do next.

I'll need to talk to users more, I guess.

I wish we have some kind of Quality Assurance department. :thinking:

**Comment by sherm1** [comment]
Damrong, can you explain what caused the MbP failures? I was thinking HydroWithFallback would be exactly equivalent to Point contact unless there was specifically-tagged hydro geometry. That seems unlikely in MbP tests unless they were specifically hydro tests or maybe tests that the model-selection feature is working properly (with those tests assuming point contact as the default).

**Comment by jwnimmer-tri** [comment]
@sherm1 If you look at the PR's pushes, I think the explanation is pretty clear.

**Comment by DamrongGuoy** [comment]
Sorry for the false alarms.  The unit test failures in Drake are easy to fix.  It's like there are two places in the code where we need to flip the two switches at the same time.

There is no more unit test failure in Drake #16569.  I do have one unit test failure in Anzu that I need to check.  Hopefully, it's just another simple fix.

**Comment by DamrongGuoy** [comment]
Update on Anzu side, I got one failed unit test with easy fix.

A simple fix (back to the past) is to restore the point contact:
```C++
builder.mutable_builder().mutable_plant().set_contact_model(
    drake::multibody::ContactModel::kPoint);
```
A better fix (step into the future) is to improve definitions of collision hydroelastic geometries and to remove the many tiny collision spheres. Here I omit details from Anzu since it's not a part of Drake.

This raises an interesting question in hydroelastic adoption. Users might already have many models with custom collision spheres for point contacts.  Switching the contact model default might trigger failures in their code.

We'll have to tell them to do `set_contact_model(drake::multibody::ContactModel::kPoint);` to restore the glorious past, while we're stepping into the bright future.  CC: @calderpg-tri

**Comment by DamrongGuoy** [comment]
Thank you @jwnimmer-tri .  I think that the unit test was set up with collision geometries for both point contact and hydroelastics.  In the past, by default, we use point contacts, so the hydroelastic parts didn't take effect. In the future, if we default to hydroelastics, the hydroelastic contact shows up and changed the behavior of the sim.

If users never set `<drake:rigid_hydroelastic>`,`<drake:compliant_hydroelastic>` tags before, the behavior should be the same for the new default.  I think that's why most of the unit tests did pass.  Only this one unit test failed.

@calderpg-tri could you confirm what I said about mixing collision geometries with point-contact + hydroelastic-contact in that unit test, please?

**Comment by calderpg-tri** [comment]
Yes, the issue is a model in Anzu that mixes collision geometries using point-contact and hydroelastic-contact. I believe the ideal solution would be to return to the original model (just using boxes and cylinders, no additional collision spheres or tweaks) with all parts using hydroelastic contact.

**Comment by DamrongGuoy** [comment]
@sherm1 #16569 has merged.  If it passes Nightly CI tonight, could you please close this issue tomorrow?

**Comment by sherm1** [comment]
I'll close it now -- we can reopen if it fails!
