### ISSUE TITLE
Upgrade to Bazel 5.1 in Provisioned

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#16865]
https://github.com/bazelbuild/bazel/releases/tag/5.1.0

Prior issue: #16447.
Prior PR: #16523.

No hurry on this, it's OK for this to wait until the 2022-04-01 externals upgrade / bionic drop time period.  I'll be running it locally in the meantime and will chime in about any local problems I see.

**Comment by BetsyMcPhail** [comment]
Note that Homebrew is still at 5.0.0

**Comment by BetsyMcPhail** [comment]
- [ ] Upgrade recommended Bazel version to 5.1.0 for Linux - #16878
- [ ] Update Linux provisioned images - Coordinate with update with #16864
- [ ] Upgrade recommended Bazel version to 5.1.0 for Mac - waiting for Homebrew
- [ ] Update Mac provisioned images

**Comment by mwoehlke-kitware** [comment]
...wheels? (macOS wheel will follow homebrew / CI provisioning, but the Linux wheels need to be updated.)

FYI, I'm running a local wheel build with 5.1.0 now... probably going to take a few hours since this invalidated all of the caching. (Would there be any value in moving Bazel provisioning to after dependencies but before Python provisioning?)

**Comment by BetsyMcPhail** [comment]
@mwoehlke-kitware [tools/wheel/image/provision-base.sh](https://github.com/RobotLocomotion/drake/pull/16878/files#diff-1d9ab263d143c0d3b9bbb66f3f1017a6c45b3100cb893ac386f3775945cfd8fe) was updated as part of the Linux PR. Where else do I need to update? I probably missed it last time as well so we may be 2 versions out of date.

**Comment by mwoehlke-kitware** [comment]
Ah, apparently my local checkout is that far out of date 😢 .
