### ISSUE TITLE
drake005 has no more disk space

### ISSUE THREAD

**Issue by tkoolen** [RobotLocomotion/drake#1693]
As shown by df -h and the build failure on https://github.com/RobotLocomotion/drake/pull/1687

**Comment by tkoolen** [comment]
Now it seems like drake006 is also out of disk space. What's going on?

**Comment by RussTedrake** [comment]
I’ve rebooted both (which should clear the tmp dirs).
Remember, on these machines, drake is checked out into a tmp dir on every commit.  I do have a script that goes through and zaps the old directories, but I leave them around for some number of days so that we can click in and see the build logs, etc.  But I think the number of pull request builds this week must have exceeded my initial expectations. :)
