### ISSUE TITLE
[SAP] Make internal:: pieces of code discoverable

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#17088]
In particular, per review comment in #17051 from @rpoyner-tri, we'd like documentation like the one for `SapLimitConstraint` to somehow make it to the public.

One idea is to publish a follow up paper where SAP's implementation in Drake is properly documented and our treatment of general constraints is described. We'd reference this paper in the SAP section to be added to our C++ modules in Doxygen.

**Comment by jwnimmer-tri** [comment]
This is a TODO based on a years-old code review, noting a hypothetical problem instead of a real problem.  If we want better documentation, we should have an issue with _that_ as the victory condition.  A bug report that remarks on a review nitpick is exactly the kind of thing that clutters our issue database with no real value.  Closing as "not planned".
