### ISSUE TITLE
gz_* need update to latest

### ISSUE THREAD

**Issue by mwoehlke-kitware** [RobotLocomotion/drake#18033]
gz_math and gz_utils need to be updated to the latest upstream versions. Both are experiencing build errors after update.

**Comment by scpeters** [comment]
I believe the `gz_math` and `gz_utils` tags are already at the latest values:

* https://github.com/gazebosim/gz-math/tags latest release number is 7.0.2
  * https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/gz_math_internal/repository.bzl#L11
* https://github.com/gazebosim/gz-utils/tags latest release number is 2.0.0
  * https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/gz_utils_internal/repository.bzl#L11

I believe the issue is that the tag formatting changed between the most recent major versions:

* https://github.com/gazebosim/gz-math/releases/tag/gz-math7_7.0.2
* https://github.com/gazebosim/gz-math/releases/tag/ignition-math6_6.13.0
* https://github.com/gazebosim/gz-utils/releases/tag/gz-utils2_2.0.0
* https://github.com/gazebosim/gz-utils/releases/tag/ignition-utils1_1.4.0

but new_release thinks the `ignition-*` tags are newer even though they have lower numbers:

~~~
gz_math_internal needs upgrade from gz-math7_7.0.2 to ignition-math6_6.13.0
gz_utils_internal needs upgrade from gz-utils2_2.0.0 to ignition-utils1_1.4.0
~~~

**Comment by jwnimmer-tri** [comment]
Thanks!  I'll update our version checker to deal.
