### ISSUE TITLE
need a lightweight c++ image loading library 

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1803]
@crogers3 recently brought in https://github.com/RobotLocomotion/drake/tree/master/drake/thirdParty/cimg , which is almost perfect but is LGPL... so it would infect our license.  

This is needed for e.g. #1616 .  Must work on mac,linux,win.  Any suggestions?

**Comment by crogers3** [comment]
Another library I had seen was [lodepng](https://github.com/lvandeve/lodepng), which I had tried out and got to work, but it doesn't seem to have an official licence, just a [small statement in its header file](https://github.com/lvandeve/lodepng/blob/master/lodepng.h#L1-L24). I also am not sure about its cross-platform capability. It worked for me on linux.

I ultimately decided to switch to cimg because it seemed more legitimate in terms of licensing and cross-platform compatibility.

**Comment by sherm1** [comment]
Lodepng's [license](https://github.com/lvandeve/lodepng/blob/master/lodepng.h#L1-L24) is non-viral and BSD-like so should be OK. Simbody has shipped with an embedded lodepng for a long time and it works on Linux/Windows/OSX. Is that enough functionality to replace cimg though?

**Comment by RussTedrake** [comment]
We aren’t actually using cimg for anything yet. We just brought it in to start
supporting terrain heightmap loading from image. So we can get by with less...

**Comment by avalenzu** [comment]
Is reading bitmaps the only required functionality?

**Comment by avalenzu** [comment]
Re. LodePNG: More specifically, it uses the [zlib/libpng](https://opensource.org/licenses/Zlib) license, word-for-word. If reading bitmaps is all we need, it seems like a good option - especially given what @sherm1 points out about it having been tested cross-platform through Simbody.

**Comment by avalenzu** [comment]
@RussTedrake, any more thoughts on requirements?

**Comment by RussTedrake** [comment]
I think it’s totally reasonable to say that any image loaded as a heightmap into
drake must be converted to a png before load. Seems like loadpng should do the
trick.
