### ISSUE TITLE
Finish implementing "multiple contacts per collision pair" for more accurate simulation

### ISSUE THREAD

**Issue by kuindersma** [RobotLocomotion/drake#181]
For example, the visualization of systems/plants/test/fallingBrickLCP shows the brick bouncing significantly off the ground. This behavior arose after the collision upgrade (a8609e66db1df43477631cd318f42f88e21f6b96 behaves normally).

**Comment by psiorx** [comment]
I've made some significant headway towards getting this to work.  Here are some screenshots of early results demonstrating the possibilities:

**Atlas Balancing on a ledge**
![ledgebalance](https://cloud.githubusercontent.com/assets/3849600/6947282/121e2cb6-d874-11e4-820e-15c22b7e19ed.png)

The contact points are generated by a convex hull model of the foot.  In this example, 16-20 contact points (not visible) are actively supporting each foot.

**Boxes stacked without their vertices touching any faces**
![stackedboxes](https://cloud.githubusercontent.com/assets/3849600/6947309/504b9ece-d874-11e4-9275-18a78e195667.png)

Although this works now, it is quite a bit slower than simply checking static contact points since in order to generate contact points dynamically, each body has to be checked against every other body several times at different orientations.

Also, since contact points can appear, disappear, or move relative to the body at every frame, I feel like the gradients that reason about the motion of the contact points in space will be wrong since the motion of the contact point is defined by the surrounding geometry rather than the forward kinematics.

Perhaps a solution that combines the advantages of both static and dynamic contact points is in order.  We could generate new contact points every n simulation ticks and add them to the list of contact points for the corresponding body.  Before adding a new point, we could check to see if it's within a threshold distance of other contact points and only add it if it's sufficiently far away.  This would encourage a uniform sampling of the contact manifold and avoid the build-up of an unnecessarily large set of contact points.  Also, the gradients would always be well defined.

We could also keep track of the time in when contact points were last active, and discard them if they've become stale.

**Comment by RussTedrake** [comment]
very cool!
