### ISSUE TITLE
Generic oriented bounding box function

### ISSUE THREAD

**Issue by rsonecha** [RobotLocomotion/drake#18421]
It would be helpful to have a generic version of the oriented bounding box function that can be used to fit a box to a **thing** (eg. [a mesh](https://drake.mit.edu/doxygen_cxx/classdrake_1_1geometry_1_1_triangle_surface_mesh.html#a972cf7cd80fb7a8357c8202a6c163612)), like we have for the axis-aligned bounding box function.

@SeanCurtis-TRI -- Based on our [Slack conversation](https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1670444168473869)

**Comment by SeanCurtis-TRI** [comment]
The linked method above applies specifically to a `TriangleSurfaceMesh` (with an analogous function for `PolygonSurfaceMesh`. The most direct solution to this issue is to add an additional method (`CalcOrientedBoundingBox()`) to those two methods. Instead of returning a pair of points, it can return the basis and the measures. (Need to decide how that quantity will be returned a tuple of rotation matrix and vector3? Or do we promote `obb.h` and `aabb.h` into the public domain? TBD.

We could also look at this as a more general problem and create a `ShapeReifier` that would return a bounding box for an arbitrary `Shape`. (The question of the return type remains for either solution.)

**Comment by SeanCurtis-TRI** [comment]
Closing this issue in favor of #15121.
