### ISSUE TITLE
**Examples for distance computation and query**  How can I get a example which shows me the method to compute distance between two object. Especially, I'd like to know the closest points and gradient message.

### ISSUE THREAD

**Issue by ZZHPKU** [RobotLocomotion/drake#18780]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sherm1** [comment]
This seems more like a request for information rather than a feature request. Please see Drake's [Getting Help](https://drake.mit.edu/getting_help.html) page. My thought is that a Stackoverflow question could get you the answer you need. If there really is no satisfactory way to get that information, please refile.
