### ISSUE TITLE
ModelVisualizer.AddModelsFromUrl()

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#18977]
Now that we are recommending that people use packages to identify their files, I *believe* we should provide `ModelVisualizer.AddModelsFromUrl()` in addition to `AddModels()`.

**Comment by jwnimmer-tri** [comment]
I agree.

For the moment, the workaround is `vis.parser().AddModelsFromUrl(...)` with the downside that the reload button would no longer be available.

As far as the function signature, another option is `AddModels(url=...)`, i.e., using a kwarg instead of a separate function.

**Comment by RussTedrake** [comment]
If we do the kwarg here, we should do it in `Parser`, too.  There are a lot of variants floating around!

**Comment by jwnimmer-tri** [comment]
The difference is that the Parser written in C++, where it's not possible to use named kwargs.

Perhaps the Python Parser API could diverge from the C++ Parser API, but so far we've been hesitant to do that, under the premise that translating a Python tutorial back down into C++ should be rote (e.g., changing method-call-dots to member-function-call-arrows), rather than altering function names.

**Comment by jwnimmer-tri** [comment]
I ended up need this for making slide deck videos, so I went ahead and implemented it.  See #19131.
