### ISSUE TITLE
ManipulationStation doesn't appear in doxygen

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#18980]
### What happened?

I went to look at the ManipulationStation documentation, but it seems to be missing.  Only the ManipulationStationHardwareInterface shows up.

![Screenshot from 2023-03-12 19-21-18](https://user-images.githubusercontent.com/6442292/224580207-b9146c95-4b35-4bc8-8ec5-6350b8044211.png)

**Comment by jwnimmer-tri** [comment]
Possibly the unnecessary forward declaration in #18268 is what did it?

**Comment by jwnimmer-tri** [comment]
+@amcastro-tri as feature reviewer on #18268, could I ask you to investigate this and see if that commit caused this regression, and maybe fix it?

**Comment by amcastro-tri** [comment]
No problem, let me try

**Comment by jwnimmer-tri** [comment]
I'll take a look.

**Comment by jwnimmer-tri** [comment]
I passed `--verbose` to the doc build command, and immediately saw that the `system_yaml_to_html` function was crashing:

```
  File "/tmp/doc_builder_temp_qxn79d0y/drake/doc/doxygen_cxx/system_doxygen.py", line 38, in system_yaml_to_html
    if "input_ports" in y:
TypeError: argument of type 'NoneType' is not iterable
```

The proximate cause for that is the _other_ thing obviously wrong with the PR (that I didn't mention before, because I didn't see any way it could be related here; oops!) -- the comment opener on the new class's overview uses `//` instead of `///`.  If you change it to `///` the Doxygen shows up fine.

Can you work on landing that fix?

I'll working on trying to fix Doxygen to give better feedback in this situation.

**Comment by amcastro-tri** [comment]
wow, nice job @jwnimmer-tri! thank you!
