### ISSUE TITLE
Having deformable models work with ExternallyAppliedSpatialForce or other external forces without contact

### ISSUE THREAD

**Issue by chen-tianjian** [RobotLocomotion/drake#19011]
**Is your feature request related to a problem? Please describe.**
We (and I believe other people too) use the ExternallyAppliedSpatialForce as interface between the multibody physics in Drake and other physics domains -- for example, we can use it for suction forces from a pneumatic system simulation, electromagnetic forces from a electromagnetic model, thrust forces from quadrotor aerodynamics model, viscous drags from a fluid model, etc. 

However, based on [this conservation](https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1678118276001869), we learned that currently the deformable models does not work with ExternallyAppliedSpatialForce.

**Describe the solution you'd like**
* A theoretical formulation that allows applying external forces to deformable bodies
* A software implementation of algorithms and ports for deformable models to connect to ExternallyAppliedSpatialForce

**Additional context**
High-level questions: 
* Based on my understanding, I guess there are no theoretical limitations that prevents us applying external forces to deformable bodies? Please correct me if I am wrong.
* If you decide to take this feature request, what is the estimated timeline?

**Comment by xuchenhan-tri** [comment]
Currently we only support gravity as an external force. One of the victory condition of this issue would be to create an example that you can follow.

I can imagine creating an `ExternalForceDensityField` class that allows users to provide a custom implementation of
```cpp
/// Computes the force density at point P given its position in the world frame.
Vector3<T> CalcForceDensity(const Vector3<T>& P_W);
```
We would then ask the user to pass in an `ExternalForceDensityField` object via a port so that deformable bodies of interest can be influenced by it.

Does that sound like something you could reasonably provide?

**Comment by chen-tianjian** [comment]
Sure, I guess that is a good plan. We can have a try when this ExternalForceDensityField port is ready. Thanks!

**Comment by xuchenhan-tri** [comment]
1. That should be possible when the feature request in this issue is implemented.
2. I'm not sure what this question is getting at. Right now we only support mesh representations of objects simulated with FEM. Of course, you are free to do whatever frame transformation as you wish as a post-process given the simulated results.

**Comment by KhomutovEvgeniy** [comment]
1. When can we expect the release of this feature?

**Comment by KhomutovEvgeniy** [comment]
> 1. That should be possible when the feature request in this issue is implemented.
> 2. I'm not sure what this question is getting at. Right now we only support mesh representations of objects simulated with FEM. Of course, you are free to do whatever frame transformation as you wish as a post-process given the simulated results.

1. When do you plan to release this feature?

**Comment by xuchenhan-tri** [comment]
We are currently aiming for 2023Q3, but the exact date may shift based on other priorities.

**Comment by xuchenhan-tri** [comment]
The feature is now supported by #20404 and an example is added to demonstrate its usage in #20629.
