### ISSUE TITLE
CI Servers Should Save Verbose Output

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#1919]
Can the CI servers use "make VERBOSE=true" so we know exactly what compiler / linker commands are being executed?

**Comment by jamiesnape** [comment]
It is enabled for new builds on the server. The flag may or may not get propagated to the externals via pods. We will see shortly.

**Comment by billhoffman** [comment]
CDash already saves that information at least for makefile builds on unix because it uses ctest launchers which capture each command.  For example, click the + on the command line here:
https://drake-cdash.csail.mit.edu/viewBuildError.php?type=1&buildid=3030
Shows the full command line for the compile.

**Comment by jamiesnape** [comment]
@liangfok Is the CDash support sufficient or would you prefer builds to be verbose in the Jenkins console too?

**Comment by jwnimmer-tri** [comment]
As a specific example, PR #1898 failed, at [link](https://travis-ci.org/RobotLocomotion/drake/builds/118062191).  How to we view the verbose output for that build failure?

**Comment by liangfok** [comment]
@jamiesnape: ditto what @jwnimmer-tri said. More verbose output in Travis CI's test would be helpful.

**Comment by jamiesnape** [comment]
Ok. I will have to put in a PR to make Travis CI more verbose.
