### ISSUE TITLE
RgbdSensorDiscrete missing ZOH on the body_pose output

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#19198]
### What happened?

From https://github.com/RobotLocomotion/drake/blob/v1.14.0/systems/sensors/rgbd_sensor.cc#L222:

https://github.com/RobotLocomotion/drake/blob/6411b8f86ef81daf74ac9dfab2fefc4bdc42f054/systems/sensors/rgbd_sensor.cc#L222-L223

The purpose of this class is to ZOH all ports of a sensor.  It's not clear why the body_pose output port should ever run ahead of the image output ports?

In #11704 when this code went in, there was a comment `// No need to place a ZOH on pose output.` which was later removed.  Even as of #11704 however, the camera could be affixed to a moving frame.  The CalcX_WB function on the sensor is not a constant.

### Version

v1.14.0

### What operating system are you using?

Ubuntu 22.04, Other

### What installation option are you using?

compiled from source code using Bazel

**Comment by SeanCurtis-TRI** [comment]
I'm not 100% sure on what the nature of the defect is. Basically, it all comes down to the assertion, "The purpose of this class is to ZOH __*all ports*__ of a sensor." (emphasis mine)

The [documentation claims](https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1sensors_1_1_rgbd_sensor_discrete.html):

> Wraps a continuous RgbdSensor with a zero-order hold to create a discrete sensor.

So, the question is, what is the nature of a discrete sensor vis a vis the `body_pose_in_world` output?

__Possibility 1__: the `body_pose` is *not* a proper property of a physical camera that shares the same discretization artifacts as the images. Instead, it is a convenience pass through on the pose that ordinarily be acquired from a different source (which may or may not be discrete)?
__Possibility 2__: It is a property and should be discretized in the same way as the image because the camera itself reports its body pose and packages it with the image data.
__Possibility 3__: We have a camera that is conceptually supposed to be 100% compatible with a discrete system and should take responsibility for breaking any continuous signals.

Certainly, the documentation doesn't allow proper inference of which possibility is *targeted* so, no matter how it gets resolved, something needs to be done to make sure its behavior is clear.

**Comment by jwnimmer-tri** [comment]
Agreed that the docs should also be improved.

I think Possibility 1 cannot possibly be what anyone wants.  That's why the lack of ZOH on the pose is a bug, since both Possibility 2 and 3 use the ZOH.
