### ISSUE TITLE
Remove maintainer-only mode for macOS CI

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#19318]
Overlooked during #18665. From https://drake-jenkins.csail.mit.edu/view/Production/job/mac-arm-monterey-unprovisioned-clang-bazel-nightly-packaging/72:

```
[2023-04-30T05:02:58.754Z] Warning: Maintainer-only tools are only supported on Ubuntu.  The "--with-maintainer-only" flag will do nothing.  This flag will be removed from Drake on or after 2023-05-01.
```

---

See #19317 work-around.  We need to change our CMake glue code to pass the maintainer-only flag only on Ubuntu, not on macOS.

https://github.com/RobotLocomotion/drake-ci/blob/653b57ea9cd14518d8a77e30baf68fe538382cc3/driver/platform.cmake#L93-L103

**Comment by svenevs** [comment]
Sorry for lack of clarity on slack.  The `MIRROR_TO_S3` conditional stays as is, that is linux only and required afaict (the [maintainer onlypython packages](https://github.com/RobotLocomotion/drake/blob/2859fe9fd264b75e078a77713a47fde542d2d8af/setup/ubuntu/source_distribution/packages-focal-maintainer-only.txt#L1) are for that at least).  For the package statement, it just needs to change to something like

```cmake
  elseif(PACKAGE)
    set(PROVISION_ARGS "--without-test-only")
    # NOTE: see 19318, maintainer-only on mac has been removed.
    if(NOT APPLE)
      set(PROVISION_ARGS "${PROVISION_ARGS} --with-maintainer-only")
    endif()
  elseif(DOCUMENTATION)
```

Since as far as I can see `--with-maintainer-only` doesn't install anything new on macOS _currently_, we can remove it from `drake-ci` before the deprecation window in `drake` closes.  Or they can go in together at the same time, no strong preference on my end.
