### ISSUE TITLE
CIrisSeparatingPlane can cause copy slicing

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#19523]
### What happened?

In https://github.com/RobotLocomotion/drake/pull/19368 we introduced the child class [CIrisSeparatingPlane](https://github.com/RobotLocomotion/drake/blob/master/geometry/optimization/c_iris_separating_plane.h), derived from `CSpaceSeparatingPlane`. But this might cause copy slicing, as both the parent and the child class have default copy and move constructor, and they don't have the virtual destructor.

Now I wonder why we introduced this `CIrisSeparatingPlane` class. It has an additional `plane_order` member field. I would think that in both CspaceFreePath and CspaceFreePolytope, it would use the plane order? So why we do not put this `plane_order` in the parent class `CSpaceSeparatingPlane` class, remove the derived `CIrisSeparatingPlane` class, and use the parent class CspaceSeparatingPlane directly?

I do feel the class inheritance is a land mine in the cspace_free_xxx files. I think @jwnimmer-tri 's suggestion on using more "has-a" relationship makes a lot of sense, at least here in this CIrisSeparatingPlane class (because I like this class to be copyable). If we decide to keep it, I like it better to be has-a rather than is-a.

cc @AlexandreAmice for the class design.
cc @jwnimmer-tri for the discussion on the copy slicing.

**Comment by AlexandreAmice** [comment]
In `CIrisSeparatingPlane` you use an enum `SeparatingPlaneOrder` as your plane order which makes sense since you only want to support a few, predeclared orders. In `CSpacePathSeparatingPlane`, I need to be able to handle all plane orders. The other main difference between `CIrisSeparatingPlane` and `CSpacePathSeparatingPlane` is the number of indeterminates in the plane parameters 

I agree that the easiest way to fix this would be to simply have the plane order be a member field of `CSpaceSeparatingPlane`, get rid of the two subclasses, and handle the difference in each classes' constructor.
