### ISSUE TITLE
DirectCollocation python bindings

### ISSUE THREAD

**Issue by lujieyang** [RobotLocomotion/drake#19937]
### What happened?

There's an error
`TypeError: Unable to convert function return value to a Python type! The signature was
        (self: pydrake.planning.MultipleShooting, result: pydrake.solvers.MathematicalProgramResult) -> drake::trajectories::PiecewisePolynomial<double>`
when I try to extract the state trajectory from `DirectCollocation` using `dircol.ReconstructStateTrajectory(result)`.

Here's a minimum working example
```python
import numpy as np
import matplotlib.pyplot as plt

from pydrake.planning import (
    DirectCollocation,
)
from pydrake.systems.primitives import LinearSystem
from pydrake.solvers import (
    Solve,
)

u_max = 1
plant = LinearSystem(
    A=[-1.0], B=[1.0], C=[1.0], D=[0.0])
context = plant.CreateDefaultContext()

num_time_samples = 21
dircol = DirectCollocation(
    plant,
    context,
    num_time_samples=num_time_samples,
    minimum_time_step=0.01,
    maximum_time_step=0.5)

prog = dircol.prog()
u = dircol.input()
dircol.AddConstraintToAllKnotPoints(-u_max <= u[0])
dircol.AddConstraintToAllKnotPoints(u[0] <= u_max)

prog.AddBoundingBoxConstraint(
    [-2], [-2], dircol.initial_state()
)

prog.AddBoundingBoxConstraint(
    [0], [0], dircol.final_state()
)
dircol.AddFinalCost(dircol.time())

result = Solve(prog)
assert result.is_success()

x_trajectory = dircol.ReconstructStateTrajectory(result)
```

### What operating system are you using?

Ubuntu 20.04

### What installation option are you using?

compiled from source code using Bazel

**Comment by jwnimmer-tri** [comment]
Yup, we can see the problem reflected [in the documentation](https://drake.mit.edu/pydrake/pydrake.planning.html#pydrake.planning.KinematicTrajectoryOptimization.ReconstructTrajectory), also. The return type there is displayed using its C++ class name, instead of the Python class name.

The fix will probably be to add the missing `py::import("pydrake.trajectories");` line to the list here:
https://github.com/RobotLocomotion/drake/blob/2abc2c84a97db33471ebd347b0efe1574fc3e2b2/bindings/pydrake/planning/planning_py.cc#L14
