### ISSUE TITLE
vSphere Instance Capping Needs Review

### ISSUE THREAD

**Issue by svenevs** [RobotLocomotion/drake#20413]
Redirect from #20410, I was experiencing problems where too many vSphere jobs were launching.  After the jenkins update, it appears the VM and Instance Cap settings got messed up, I set them both to 6.

We only have one node now though, and I do not recall the old instance settings / it may be hard to rediscover that without pausing Jenkins on a Friday.  @BetsyMcPhail do you remember what our maximum values were for VM and Instance cap for the vSphere cloud in Jenkins?  Is 6 too many?

Criteria for closing this ticket would either be to

1. Relaunch all the x86 CI on #20410, and verify that they all pass.  This will bog down CI for quite some time.  However, previously, a number of them just ended up failing.
2. Try running the command that launches all CI on a PR to see if everything is still working?

While it may be possible to find this information without interrupting jenkins, I don't think that (or restoring the old one to find the values) is worth the time or effort.  Just something I clearly missed in the upgrade and wanted to let others know what was going on behind the scenes and what my current solution was (capping to 6).

CC @jwnimmer-tri

**Comment by BetsyMcPhail** [comment]
Some history of VSphere Instance Cap:

https://github.com/RobotLocomotion/drake/issues/18177#issuecomment-1307906921
https://github.com/RobotLocomotion/drake/issues/16403#issuecomment-1276590372

https://github.com/RobotLocomotion/drake/issues/19097#issue-1647700340

Following the change to one x86 node, the `Template Instance Cap` was set at **2**.

I don't see any reference to adjusting `Max number of VMs online`. I believe this was set to 0 to allow VMs to be spun up for maintenance without affecting Jenkins.

I updated Jenkins to `Template Instance Cap`: 2 and `Max number of VMs online`: 0 (unlimited).

I'm going to close this now without further testing, if we run into x86 issues in the future we can revisit, otherwise it's not worth spending a lot of time testing.
