### ISSUE TITLE
VTK Patches to Upstream

### ISSUE THREAD

**Issue by svenevs** [RobotLocomotion/drake#20455]
There are a handful of patches being vendored right now that we want to upstream:

- [x] [`[vtk] Remove a spurious dependency on VTK::utf8`](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/vtk_internal/patches/common_core_noutf8.patch)
- [x] [`[vtk] Fix warnings in VTK::CommonCore`](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/vtk_internal/patches/common_core_warnings.patch)
- [X] [`[vtk] Fix warning in VTK::CommonDataModel`](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/vtk_internal/patches/common_data_model_warnings.patch)
- [x] [`[vtk] Fix PNG reader error reporting`](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/vtk_internal/patches/io_image_png_messages.patch)
- [X] [`[vtk] Remove stack trace printing in Rendering::OpenGL2`](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/vtk_internal/patches/rendering_opengl2_nobacktrace.patch)
    - Questionable, I want to ask internally, personally my vote is to remove that from VTK for the reasons you bypassed it in drake, but I don't know its origin or history.

CC @jwnimmer-tri @BetsyMcPhail

**Comment by jwnimmer-tri** [comment]
I just double-checked that the list of patch is correct.

The first five are pretty clear and are good to move forward.

The last one (XOpenGL error) is a bit different now since the summary was written.  It's might not be worth trying to change anything upstream -- but if you like, I would be OK funding the change to remove the `abort()` calls and instead only ever using `vtkErrorMacro` and then an early-`return` statement.  Drake doesn't urgently need that though, so if it's difficult we can skip it.  If it there is interest from the VTK side, I'm happy to be a good citizen and fund that improvement.

**Comment by mwoehlke-kitware** [comment]
https://github.com/RobotLocomotion/drake/pull/20710 is related.

**Comment by kwryankrattiger** [comment]
This seems to be fixed in master already: [[vtk] Fix warning in VTK::CommonDataModel](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/vtk_internal/patches/common_data_model_warnings.patch)

Here is a pass at removing the stack trace by making it only print in Debug builds: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10802

**Comment by jwnimmer-tri** [comment]
> I think that completes the list then other than me opening a PR to label the DataModel warning patch as unneeded in newer VTK.

Agreed.  (Specifically -- our patch is moot now not because we upstreamed it, but rather because [this commit](https://gitlab.kitware.com/vtk/vtk/-/commit/2ab127a520ab2c689dc113a35d16b0062ca46547) rewrote the code.)

> The abort issue is going to be slightly more involved to fix properly in VTK, so that could a on a wish list for a later date?

It's OK with me if we skip it.  My only reason to do it would be as a good citizen funding open source, we don't actually need it in Drake.

**Comment by svenevs** [comment]
#20746 was already open so I went ahead and finalized it.

> It's OK with me if we skip it. My only reason to do it would be as a good citizen funding open source, we don't actually need it in Drake.

Thank you :slightly_smiling_face:  Lets discuss briefly on Thursday, right now my vote would be to bump this back to On Deck, and we'll find the right time to fix the `abort()` stuff.

**Comment by jwnimmer-tri** [comment]
I'm happy to keep "clean up OpenGL aborts" on deck, but once that's the last thing remaining let's open a new, more focused issue just for that -- it's really about "Do novel VTK surgery" more than really "upstream some Drake patch".

**Comment by svenevs** [comment]
> let's open a new, more focused issue just for that

=> #20767

Thanks!
