### ISSUE TITLE
Slow matlab tests are slow

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#2068]
https://drake-cdash.csail.mit.edu/viewTest.php?buildid=7749

Sort by "Time".  The top 18 slowest matlab tests take about 60 CPU minutes to run, out of ~330 CPU minutes for the entire suite.

Strandbeest in particular is a real winner, at ~15 CPU minutes per PR, of which ~9 minutes is pure latency -- a CI run can never finish in <10 minutes because of it.

Is there any way to make these programs finish more quickly?  At least for the examples, perhaps having CTest run them for a fraction of their default simulation duration would be just as good of a test, but help regression testing run much more quickly?

Looking to perhaps @RussTedrake for suggestions.

**Comment by RussTedrake** [comment]
Yes — this has been on my mind, too.  We also have some tests that I would like to be running but we are not because they are too slow.

For long-running simulations (like Strandebeast, when it is working), I agree that a short sim is sufficient to test.  The reason the default is long is because the matlab test used to also have to function as examples which did something interesting when a user ran them with no arguments.  Now that we declare the matlab tests explicitly in the cmakelists files, we can also pass arguments in to the tests.  So could add an optional input argument to have the default behavior of that method be to simulate for a visually appealing amount of time, but have the unit test just simulate for a very short time.

Is there a standard development solution for adding regression tests to the system which are not run for CI?  For instance, it looks like we could restrict a test to only the nightly configuration in [add_test ](https://cmake.org/cmake/help/v3.0/command/add_test.html).  @RobotLocomotion/kitware — what are the ctest recommended best practices for this?

**Comment by billhoffman** [comment]
We could add labels to the tests.  Then have the CI test exclude LONG_RUNNING_TESTS for PR and continuous builds.

**Comment by RussTedrake** [comment]
but I think developers should probably skip them by default, too?  On make test?

**Comment by billhoffman** [comment]
If you don't want developers to run them then you would have to have a cmake cache option that turned them off.

**Comment by jwnimmer-tri** [comment]
So, this discussion has gone pear-shaped.  I had intended to have this ticket indicate that matlab CI builds are slow, and that we should pass CTest flags to examples to make then run more briefly.

Adding opt-in endurance tests should be filed under a different issue.

**Comment by jwnimmer-tri** [comment]
Russ' regression test request has been moved into #2078.

**Comment by jwnimmer-tri** [comment]
I think with the two good options at hand now (the `add_matlab_test` mechanism where we can pass smaller `tspan` to simulate during testing per this issue; and #2078 to evict tests from the PR builders), this issue is ripe for some high-payoff improvements.  I bet with some fixes here, ninja, and 36-core AWS machines, we could hit the 15-minute mark on linux PR turnaround!

**Comment by david-german-tri** [comment]
@jamiesnape has been doing a bunch of evictions.  The longest presubmit MATLAB test is now about 4 min, 30 sec: https://drake-cdash.csail.mit.edu/viewTest.php?buildid=20734

We're currently running about 35 minutes for the MATLAB presubmit build, about 20 minutes of which are test execution.  I took a look at ratcheting down execution times:

For the [slowest-remaining test](https://github.com/RobotLocomotion/drake/blob/59a62d2dbe484b713c6e25561bdc3d647a4d17a7/drake/examples/SimplePulleys/ChineseYoYo.m), it's not obvious to me whether it's safe to let the test run for less than `[0 5]`.  Does anyone have ideas how to make this call?  

The [second-slowest test](https://github.com/RobotLocomotion/drake/blob/59a62d2dbe484b713c6e25561bdc3d647a4d17a7/drake/examples/Quadrotor/runMixedIntegerSimpleForest.m) isn't a simulation:

[Third-slowest](
https://github.com/RobotLocomotion/drake/blob/59a62d2dbe484b713c6e25561bdc3d647a4d17a7/drake/examples/Acrobot/runSwingUp.m), ditto.

[Fourth-slowest](https://github.com/RobotLocomotion/drake/blob/59a62d2dbe484b713c6e25561bdc3d647a4d17a7/drake/examples/grasping/forceClosure/test/testSynthesizeGrasp.m) has assertions (yay!) and appears to be a bunch of test cases glued together.

So I'm not sure there is much low-hanging fruit left.  There could be low-hanging test coverage fruit if we scaled back down some of the LONG_RUNNING_TESTS and brought them back into presubmit, but I'm not inclined to do that until we start seeing them break.

**Comment by david-german-tri** [comment]
We've continued to make gradual progress on this - longest presubmit test is now 3m 38s - so I'm going to close.  https://drake-cdash.csail.mit.edu/viewTest.php?buildid=145280
