### ISSUE TITLE
Lagged and Similar contact models limit stiffness like SAP does in near-rigid regime

### ISSUE THREAD

**Issue by jbinagia** [RobotLocomotion/drake#21510]
**Is your feature request related to a problem? Please describe.**
My feature request is related to the following problem, described on the Drake slack channel ([link](https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1717082805357119)).

In short, users of Drake from Amazon Robotics (the Gemini team) would like to use the new Lagged / Similar contact models, for the reasons discussed in the [Drake documentation](https://drake.mit.edu/doxygen_cxx/namespacedrake_1_1multibody.html#aa1d02176591187cb83e77e9ff779d679) and paper ["A Theory of Irrotational Contact Fields"](https://arxiv.org/pdf/2312.03908#page=5.12) (i.e. Hunt-Crossley dissipation, no gliding artifact in slip, etc.). Unlike the SAP model, these two models exhibit unstable plane-on-plane contact for floating models if the modulus (or stiffness) is too large, e.g. see thread [here](https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1716474655591939) and the following video:

https://github.com/RobotLocomotion/drake/assets/30089571/66bfb879-4926-4cb2-968c-8cfa53872991

While we can decrease the hydroelastic modulus of our floating models, this creates a new issue of deep penetration when these models are picked up under strong suction (the suction force being much larger than the weight of the model itself). A video illustrating this behavior alongside a simple reproduction in pydrake (using deepnote) is provided in the additional context. Thus, we would like to continue using the modulus value of ~1e6 to prevent deep penetration with suction cups.

The SAP model circumvents the instability shown in the video above by automatically limiting stiffness for near-rigid contact. This allows us to use a modulus large enough to prevent deep penetration between suction cups and floating models while also removing unwanted instability for floating model stacked on top of one another.

Another way to state my request is: I would like to be able to use the Lagged / Similar models without having to re-adjust all the moduli for my models, moduli that presently work well alongside the SAP model.

**Describe the solution you'd like**
According to @xuchenhan-tri, there is nothing inherent in the Lagged and Similar models to prevent giving them the same "stiffness limiting" behavior that the SAP model currently possesses. This is my preferred solution since it provides consistent behavior across the three contact models and is robust for users of the sim; i.e. the sim effectively automatically handles contacts that it knows to be unstable due to poor conditioning in the limit of rigid contact.

**Describe alternatives you've considered**
N/A - although I am open to suggestions.

**Additional context**
- [Deepnote notebook](https://deepnote.com/workspace/drake-243a-4ff108f2-1127-4473-b0a6-96edd49a6e86/project/Tutorials-Duplicate-82c0dd10-08a8-4538-9b52-fdac87b63218/notebook/suction_cup_test-fbeb0d00023040868928cf5fe4c2c543) reproducting deep penetration between suction cup and floating model. Deep penetration only occurs when using Similar / Lagged with the smaller modulus that they require (~2e4 Pa vs ~1e6 Pa used with SAP).
- Illustration of deep penetration when floating model is picked up under suction with ~1e4 Pa modulus and Lagged / Similar:

https://github.com/RobotLocomotion/drake/assets/30089571/2f26e171-7c4d-4a70-9f3f-4e57b724afec

- Illustration of shallow penetration (desired) when floating model is picked up under suction with ~1e6 Pa modulus and SAP:

https://github.com/RobotLocomotion/drake/assets/30089571/d7ff5a13-eb3e-455e-95c6-09e08bba83b5
- Analogous videos of the issue inside Gemini are provided in the Drake slack channel ([link](https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1717082805357119))

**Comment by amcastro-tri** [comment]
A little update on this:

This is not a problem inherent to kSimilar or kLagged. The same problem does happen with kSap, but it so happens to show up later in the sim. Simply run your example to `sim_time=20` (instead of 5) and you will also see it with `kSap`. 

Regularization is not the reason for differences. At E=1e6, regularization almost plays no effect (except for a few triangles). The differences are due to different dynamics in the model. At the (very) large dissipation used for the kSap model, things just happen at a slower rate.

Also, geometry plays an important role. The problem happens much more slowly as we use a smaller resolution hint for the cylinder. Still the problem shows up if we run long enough.

For additiona info, I verified that we get a fan of these many triangles for the cicular bases of the cylinder:
  - 8 at rez_hin = 0.02
  - 6 at rez_hin = 0.03
  - 4 at rez_hin = 0.04

I am still investigating, but this seems a curious problem with the hydro representation used for these geometries.
@SeanCurtis-TRI and @DamrongGuoy might want to also take a look at this.

**Comment by jbinagia** [comment]
@amcastro-tri Thanks for looking into this - I just wanted to make an important clarification. I agree that regularization plays no role in the deep penetration issue. My point was that that with `kSap`, deep penetration is completely avoided by using a modulus E = 1e6. For `kSimilar` and `kLagged`, E = 1e6 cannot be used because those models do not apply regularization for near-rigid contact (recall our earlier thread [here](https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1716474655591939) where that was discussed in the context of two floating models making plane-on-plane contact due to gravity)

**Comment by SeanCurtis-TRI** [comment]
@amcastro-tri I'm not sure what you're referring to by "a fan of these many triangles for the circular bases of the cylinder"?

Can you provide guidance for what @DamrongGuoy or I would need to do to observe what you're talking about? Otherwise, there's nothing much we can do to shed any further light.

**Comment by SeanCurtis-TRI** [comment]
@amcastro-tri If you want us to comment on something *specific* then you should fuel that comment with something *specific".

1. The deepnote linked doesn't run successfully without being edited (`Ecombined` is commented out in the first block but used in the fourth).
2. The videos in slack don't highlight the thing I think you want me to comment on. And if one does, I'm not sure which one does because there are multiple videos in that conversation.

All that aside, and having run the simulation and observed the visualization, it seems you're trying to make a point about the tessellated cylinder.
  - The tessellated cylinder:
      - I agree that the resolution hint provided (twice the size of the cylinder) will produce a cylinder that looks like a rectangular box.
      - Changing it to less than the radius makes a smoother approximation.
      - The tessellation behaves as expected.
  - The contact surface
      - The contact surface is *basically* what I would expect.
         -  I must admit to being mildly surprised that the faces of the contact surface that align with the barrel of the cylinder aren't being culled away. But, regardless, I assume that the contribution along those faces are slight (because of the contact normals - they should all basically cancel each other out.) But, in retrospect, I believe the culling cutoff is more generous than simply perpendicular, so, that's why they're included.
     - Given the nature of the contact (box towards cylinder end cap), I shouldn't think that resolution of the cylinder should do much to affect the simulation outcome. It's true that increasing the resolution asymptotically increases the surface area of the contact surface (thereby increasing the integral of the pressure). I can imagine that would lead to the largest behavior change when comparing the coarsets (four-sided) approximation with the next coarsest (eight-sided). But each successive refinement should have a decreasing impact on the dynamics.

**Comment by amcastro-tri** [comment]
Sorry for the trouble @SeanCurtis-TRI. I only pinged you gusy because I found the behaviour "curious" at least. I figured you guys would find this curious as well.
No action item thus far, just food for thought for the moment.

**Comment by amcastro-tri** [comment]
The problem here essentially that we'd like to increase stiffness to model these suction cups. However this leads to instablities for flat contact surfaces. This is best described in #21514. Therefore I am closing this issue since ##21514 does a better job at describing the actual problem.
