### ISSUE TITLE
Review drake-external-examples mac ci setup

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#21851]
Reported via slack https://drakedevelopers.slack.com/archives/C270MN28G/p1724675651726299

**Comment by jwnimmer-tri** [comment]
The homebrew pile of yaml for DEE's github runners has always been, and will always be, a complete disaster.  I am not keen to try to make it better, since the ceiling for how good it can become is in down near hades somewhere.

When we have some acute problem where we need to fix a broken DEE, I am happy for cleanup to happen as part of fixing bugs, but I don't want to invest in cleanups that don't solve any actual bugs.
