### ISSUE TITLE
Strange Behavior when Setting Light Intensity with Meshcat::SetProperty 

### ISSUE THREAD

**Issue by cohnt** [RobotLocomotion/drake#21982]
### What happened?

If you run the following python code, the intensity of the ambient light is set to 2, as expected.
```
from pydrake.all import StartMeshcat
meshcat = StartMeshcat()
meshcat.SetProperty("/Lights/AmbientLight/<object>", "intensity", 2.0)
```
But if you instead call it without the decimal point, it sets the intensity to 1.
```
from pydrake.all import StartMeshcat
meshcat = StartMeshcat()
meshcat.SetProperty("/Lights/AmbientLight/<object>", "intensity", 2)
```

**Comment by jwnimmer-tri** [comment]
The binding is overloaded to take the `value` as either `bool` or `float` or `str`.  I imagine that when given an integer, it is choosing `bool`.  The bool overload should probably be marked with `noconvert` so that it only accepts literal bools (https://pybind11.readthedocs.io/en/stable/advanced/functions.html#non-converting-arguments).

**Comment by cohnt** [comment]
Good to know! Looks like [this guy here](https://github.com/RobotLocomotion/drake/blob/9339312b5eb6267b2916f2f9e3b88e92bef59a53/bindings/pydrake/geometry/geometry_py_visualizers.cc#L347)? I'll PR the fix later this week.

**Comment by jwnimmer-tri** [comment]
Yes, that's _probably_ the overload where things are going wrong.  I would need to see some test case as final proof, but that would be the place I'd suggest starting.
