### ISSUE TITLE
issue with workspace

### ISSUE THREAD

**Issue by Dawitsco** [RobotLocomotion/drake#22039]
### What happened?

after install prerequisite file without bazel, i encountered this error:

INFO: Reading rc options for 'version' from /home/dawitsco/drake_C/drake/tools/bazel.rc:
Inherited 'common' options: --enable_workspace=true --enable_bzlmod=false
ERROR: --enable_workspace=true :: Unrecognized option: --enable_workspace=true
The Drake source distribution prerequisite setup script has experienced an error on line 20 while running the command sudo -u "${SUDO_USER}" bash "${user_env_script

### Version

ubnntun

**Comment by jwnimmer-tri** [comment]
Our [new issue page](https://github.com/RobotLocomotion/drake/issues/new/choose) asks that help with build problems be posted on StackOverflow, instead of filing bugs.  This problem does not seem like a bug -- the `Unrecognized option: --enable_workspace=true` indicates a too-old version of Bazel is being used, likely the `bazel-bootstrap` package mentioned in #22038.

Drake's installation docs are https://drake.mit.edu/installation.html.  We recommend using a pre-built binary release (pip, apt, or tgz) to get started.  For examples of using Drake as a dependency in your own project, see https://github.com/RobotLocomotion/drake-external-examples/.
