### ISSUE TITLE
Build Instructions Should Be Updated to Specify Out-Of-Source Builds

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2283]
Out-of-source builds are desirable since it enables developers to maintain multiple configurations (e.g., `Debug`, `Release`, and `RelWithDebInfo`) based on the same code base. It also keeps build artifacts in a directory that's separate from the code that is version controlled, which is cleaner, requires fewer entries the `.gitignore` file, and allows us to reset our build environment by deleting a directory.

The Windows installation instructions have already been updated to promote out-of-source builds. We should do the same for the Linux and OS X installation instructions.

**Comment by jwnimmer-tri** [comment]
We need to be sure that CI covers this new configuration before (or concurrent with) suggesting it to developers.

And even better that updating the docs (which will certainly require some tweaks), we should just make Drake do the right thing by default, instead of telling people to toggle the options every time.
