### ISSUE TITLE
Remove requirement on pkg-config for Windows builds

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#2483]
Removing the requirement for all platforms would be an improvement, but not essential.

**Comment by mwoehlke-kitware** [comment]
#2486 will help here. Along the same lines, this will require teaching LCM to find glib without pkg-config; doing that in CMake-ified LCM (vs. the lcm-pod repo) is likely preferable.

We might also want to consider dropping support for libbot rather than fixing that; at this point, are we really still using it for anything?

**Comment by jamiesnape** [comment]
Closing since Windows is no longer supported.
