### ISSUE TITLE
Remove all manually created makefiles

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#2484]
All makefiles should be generated by CMake.

**Comment by david-german-tri** [comment]
This ticket refers to the top-level Makefile, and to custom externals / CMake PODS.

**Comment by jwnimmer-tri** [comment]
@RussTedrake Let's discuss PODS here instead of in PR #2758.

We have a goal in #2482 of not relying on PODS within Drake to build our externals -- to use CMake exclusively to compile everything within `drake-distro` (to the extent possible).  That seems fine.

The question is, should we still provide a `drake-distro/Makefile` in our source tree, for projects that want to use Drake as one of their externals -- i.e., a simple Makefile with just the `all` target that shells out to CMake to do the build + install into `BUILD_PREFIX`.

Does anyone still need or use that capability?

**Comment by wxmerkt** [comment]
OpenHumanoids needs the ``drake-distro/drake/Makefile``

**Comment by jamiesnape** [comment]
@wxmerkt Would a particular target generated by CMake work or do you physically have to have a `Makefile` at that path?

**Comment by wxmerkt** [comment]
@jamiesnape Drake's being called from a top-level PODS build system so we do need to have a Makefile at that path.

**Comment by mwoehlke-kitware** [comment]
> OpenHumanoids needs the `drake-distro/drake/Makefile` (as we provide required externals ourselves)

The file you reference is https://github.com/RobotLocomotion/drake/blob/master/drake/Makefile, correct? I take this to mean you are building *just* drake, and not the drake superbuild? Do you need [`<drake>/Makefile`](https://github.com/RobotLocomotion/drake/blob/master/Makefile)?

**Comment by wxmerkt** [comment]
@mwoehlke-kitware Correct, we do not need ``drake/Makefile``, only ``drake/drake/Makefile``. I've seen Jeremy's comment only referencing the superbuild-Makefile, but commented given the title of the issue to remove _all_.

**Comment by jwnimmer-tri** [comment]
Thanks, that's very helpful to know.

**Comment by david-german-tri** [comment]
OK, I'm going to create a PR that zaps the top-level Makefile, since it appears that its only purpose in life is now to confuse people.

**Comment by mwoehlke-kitware** [comment]
@david-german-tri: #2809

**Comment by mwoehlke-kitware** [comment]
Isn't this dealt with to the extent possible? Last I knew, folks were insistent that we keep the remaining `Makefile`...

**Comment by david-german-tri** [comment]
Agreed.
