### ISSUE TITLE
Implement Gain system

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#2985]
For this system:
- It is direct feedthrough
- `y = k * u` where k is the gain constant.

Where should the constant of the system go? somehow into the context as a "parameter" so we can allow four auto-differentiation? Thoughts @david-german-tri, @sherm1?

**Comment by sherm1** [comment]
> Where should the constant of the system go? 

Gain should be a Parameter to the system block so that it can be exposed at the System Diagram level like an Input. We don't have that yet though so I would suggest just making it a type `T` member of the `Gain<T>` System class. We can still differentiate with respect to it but to do so you have to know there is a Gain block inside and dig it out to get to its Gain-specific methods.

**Comment by david-german-tri** [comment]
Agreed with @sherm1 on all counts - the expedient thing to do right now is just pass it into the constructor.

**Comment by amcastro-tri** [comment]
Closed by #3097
