### ISSUE TITLE
Turn off msvc-64 on pre-merge jenkins builds

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#3054]
I propose that we should turn off `msvc-64` jenkins builds in the pre-merge matrix.  I believe that every pre-merge msvc error has always shown up either in 32 only, or else both 32 and 64 (never on 64 only).  This should substantially help conserve our Jenkins resources, since pre-merge builds are much more numerous than post-merge builds.

@david-german-tri @jamiesnape @BetsyMcPhail what do you think?

**Comment by jamiesnape** [comment]
I agree. We are working with AWS to finalize a yearly budget, so make a decision on this quickly would be good. Note that individual Windows instances on average cost us 5x the price of individual Linux instances, and offer 90% build time in the first and last hours due to increased startup and shutdown overhead. They are also more unreliable.

**Comment by jamiesnape** [comment]
I agree. We are working with AWS to finalize a yearly budget, so make a decision on this quickly would be good. Note that individual Windows instances on average cost us 5x the price of individual Linux instances, and offer 90% build time in the first and last hours due to increased startup and shutdown overhead. They are also more unreliable.

**Comment by david-german-tri** [comment]
SGTM as well.  @RussTedrake, is that OK with you?

**Comment by RussTedrake** [comment]
yes.  i think msvc-32 should catch what we need.

**Comment by jamiesnape** [comment]
Done.
