### ISSUE TITLE
Consider turning on hidden visibility on clang and gcc

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#3059]
MSVC only includes symbols in a DLL if they are explicitly exported.  Clang and gcc have an option to do the same, but it is off by default.  We should consider turning it on.  This will decrease the number of "surprise" Windows CI failures developers experience, and possibly make our dynamic libraries a little slimmer.

The macros to identify interface symbols in clang and gcc are different than for MSVC, but are already set up correctly in the `_export.h` files.  

We should also consider turning on the flag that makes failure to find a library a hard error.

**Comment by liangfok** [comment]
Can you point me to some background reading that explains what "hidden visibility" means in this context?

**Comment by david-german-tri** [comment]
For gcc, see https://gcc.gnu.org/wiki/Visibility.  I assume clang is similar.  

I believe the CMake flag that controls this and similar options is `CMAKE_CXX_VISIBILITY_PRESET` (though I haven't actually tested).

http://stackoverflow.com/questions/17080869/what-is-the-cmake-equivalent-to-gcc-fvisibility-hidden-when-controlling-the-e

**Comment by mwoehlke-kitware** [comment]
This is... *mostly* fixed by #3065. The remaining issue is with the MATLAB code, which appears to be missing export decorations. My initial attempts to fix it were not very successful.

Eventually I think we definitely want to take another crack at this, as it will be required to move to `matlab_add_mex` (`FindMatlab.cmake`), which forces hidden visibility. (For #3065, I worked around it by having the mex stuff revert to default visibility.)

**Comment by david-german-tri** [comment]
With Windows gone, we're only going to back off hidden-visibility, not expand it.  Closing.
