### ISSUE TITLE
Certain long-running MATLAB tests sporadically time out in CI

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#3149]
- runPassiveDownhill
- testMultipleTaskSpaceRRTStar
- testTaskSpaceRRT

They are particularly timeout-prone on Mac in debug mode.  We should consider either extending the timeouts or finding ways to shorten the test.

**Comment by ggould-tri** [comment]
This also appears to apply to: 
 * RigidBodyManipulatorMemoryTest
 * systems/plants/constraint/test/RelativeGazeTargetConstraintTest
 * systems/plants/constraint/test/RelativeQuatConstraintTest
 * systems/plants/constraint/test/testPostureConstraint

Because long-running matlab tests were just added to the continuous build, all of these tests will be disabled.  This issue will remain open, and the disabling will reference this issue in both source comments and commit messages.

**Comment by jamiesnape** [comment]
Also:
* examples/Atlas/runDRCPracticeTerrain

**Comment by RussTedrake** [comment]
i believe these have been disabled and will not be fixed (in the matlab versions)
