### ISSUE TITLE
Rename drake-distro/drake/examples/Cars to drake-distro/drake/automotive

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#3406]
I think the library of vehicular and/or automotive systems (and related toolkit elements) should be an in-tree tookit as part of Drake.  It will very soon outgrow a simple example, if it hasn't already.  Let's agree to move it into a new home at the `drake-distro/drake/mysomething` top level.  If there are any objections to that, speak up now.

(I will debate the name for `mysomething` in a second message, to better allow for voting and/or discussion.)

**Comment by jwnimmer-tri** [comment]
My best suggestion is `drake-distro/drake/automotive`.  @RussTedrake do you have any feelings if that is an appropriate vocabulary to use for your vision?

**Comment by liangfok** [comment]
I wonder whether we could create general bins that transcend "automotive". Something like:

* `drake-distro/drake/actuators`
* `drake-distro/drake/common`
* `drake-distro/drake/controllers`
* `drake-distro/drake/examples`
* `drake-distro/drake/force_elements`
* `drake-distro/drake/models` -  This may be a submodule per #3257.
* `drake-distro/drake/models_tri` - This may be an optional submodule per #3257.
* `drake-distro/drake/optimizers`
* `drake-distro/drake/parsers`
* `drake-distro/drake/perception`
* `drake-distro/drake/planners`
* `drake-distro/drake/plants`
* `drake-distro/drake/rigid_body_mechanics`
* `drake-distro/drake/road_networks`
* `drake-distro/drake/sensors`
* `drake-distro/drake/simulation` - maybe "solvers" instead of "simulation"?
* `drake-distro/drake/system_id`
* `drake-distro/drake/systems`

An automotive application could then pick-and-choose various components from each of the above bins.

**Comment by jwnimmer-tri** [comment]
@liangfok I think many of those make sense, and should happen (or already exist), but with `mysomething` I'm looking for a home for the actual automotive-specific elements, and applications that incorporate them.  That is, all of the vehicular system blocks we're going to write, agent models, etc.  Generic planners or sensors and such should certainly be available outside of the `mysomething` directory.

**Comment by liangfok** [comment]
:+1: for `drake-distro/drake/automotive`

**Comment by RussTedrake** [comment]
I like “vehicles” better, but agree that it is not sufficient.  +1 for automotive.

**Comment by jwnimmer-tri** [comment]
Yeah.  I tried to find a variant of "vehicles" that worked, but to no avail.  Thanks for the input.

**Comment by maddog-tri** [comment]
How about "cars" instead of "automotive"?  awmomotiff is a mouthful and the 2.5x character count does not express any greater or deeper meaning than simply "cars".

**Comment by liangfok** [comment]
Well, in my mind, "automotive" encompasses a wider set of vehicles than "cars". For example, I would include a truck in the "automotive" category but not in a "car" category.
