### ISSUE TITLE
CMake sometimes finds gflags in a different Drake checkout

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#3433]
See @ggould-tri's post below for the original report.  I can reproduce with the following steps:

```
$ mkdir 3433 && cd 3433
$ git clone https://github.com/RobotLocomotion/drake.git old-distro
$ git clone https://github.com/RobotLocomotion/drake.git new-distro

# Reset old-distro to before PR 3345, and build.
$ cd old-distro
$ reset --hard a3fda8ccbef28e8d9606b4c50498ecc75aaa9d91
$ mkdir build && cd build && cmake .. -G Ninja && ninja

# Try to build new-distro at HEAD. This fails on a linker error.
$ cd ../../new-distro && mkdir build && cd build && cmake .. -G Ninja && ninja
```

This is incredibly sketchy because the resulting error message shows that CMake actually rummaged around two directories up to find `gflags`, pulling it from neither `new-distro` or `old-distro`, but from a cousin directory under `3186`, a sibling of `3433`.  How?  Why?  If CMake can roam that far afield, I'm not even sure how to construct a clean reproducing case.

```
[133/678] Linking CXX shared library lib/libdrakeCommon.so
FAILED: : && /usr/lib/ccache/c++  -fPIC -Werror=all -Werror=ignored-qualifiers -DGTEST_DONT_DEFINE_FAIL=1 -DGTEST_DONT_DEFINE_SUCCEED=1 -DGTEST_DONT_DEFINE_TEST=1 -O3 -DNDEBUG  -Wl,--no-undefined -shared -Wl,-soname,libdrakeCommon.so -o lib/libdrakeCommon.so common/CMakeFiles/drakeCommon.dir/drake_assert.cc.o common/CMakeFiles/drakeCommon.dir/__/generated/drake/common/test/drake_path.cc.o common/CMakeFiles/drakeCommon.dir/drake_throw.cc.o common/CMakeFiles/drakeCommon.dir/functional_form.cc.o common/CMakeFiles/drakeCommon.dir/nice_type_name.cc.o common/CMakeFiles/drakeCommon.dir/polynomial.cc.o common/CMakeFiles/drakeCommon.dir/text_logging.cc.o -L/media/dgerman/ssd-build/3433/new-distro/build/drake/lib  -L/media/dgerman/ssd-build/3433/new-distro/build/install/lib /media/dgerman/ssd-build/3186/drake-distro/build/externals/gflags/lib/libgflags.a -lpthread -Wl,-rpath,/media/dgerman/ssd-build/3433/new-distro/build/drake/lib:/media/dgerman/ssd-build/3433/new-distro/build/install/lib: && :
/usr/bin/ld: /media/dgerman/ssd-build/3186/drake-distro/build/externals/gflags/lib/libgflags.a(gflags.cc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/media/dgerman/ssd-build/3186/drake-distro/build/externals/gflags/lib/libgflags.a: error adding symbols: Bad value
```

@ggould-tri @sammy-tri FYI

**Comment by ggould-tri** [comment]
Thanks, David.  Recap of my experience below:

- I had a clone of my personal drake fork in `~/git/drake-ggould`, which was up-to-date
- I had a clone of Naveen's personal drake fork in `~/git/drake-naveen`, which was two weeks out of date
- I built in the top level of my clone `~/git/drake-ggould` using https://github.com/ggould-tri/public-sandbox/blob/master/Scripts/build-drake.sh (which pretty much just encapsulates the documented build process)
- The build failed due to a linker error on `gflags` and the output indicated that it was using the `libgflags.a` from `~/git/drake-naveen`

Unfortunately I then concluded the problem was that I had done something wrong and deleted all of the directories involved.  Only when @sammy-tri mentioned the same problem did I realize otherwise.

**Comment by jwnimmer-tri** [comment]
My local builds also have buckets-o-fun going on with gflags linking now (linebreaks added for readability):
```
jwnimmer@call-cc:~/jwnimmer-tri/drake-distro/build/debug/drake/bin$
readelf -d rigidBodyLCMNode
...
Library rpath: [
  /home/jwnimmer/jwnimmer-tri/drake-distro/build/debug/drake/lib:
  /home/jwnimmer/jwnimmer-tri/drake-distro/build/clang-debug/externals/gflags/lib:
  /home/jwnimmer/jwnimmer-tri/drake-distro/build/debug/install/lib:]
```

See how a different build variant crept in there?
