### ISSUE TITLE
Consider not building dReal by default (i.e., setting WITH_DREAL to false by default)

### ISSUE THREAD

**Issue by tkoolen** [RobotLocomotion/drake#3505]
This is just a suggestion, feel free to share your thoughts. 

My main reason for suggesting this is that building dReal adds quite a bit to build time, while only a small (albeit hopefully growing) subset of users will use its functionality. Of course, there would still be CI builds that include dReal, to make sure there's no bit rot. Perhaps another option would be to get dReal from a precompiled tarball.

cc: @soonho-tri as the main stakeholder, what do you think?

**Comment by soonho-tri** [comment]
I think it's reasonable to switch to `default=off` for now. I'm still working on the integration, so for now, it's not useful to turn it on anyway.

I've added PPA (for Ubuntu/Debian) and Homebrew support for dReal. One thing I can do is to list dReal as a dependent package of drake (i.e. `sudo apt-get install dreal` after adding PPA) and provide `FindDreal.cmake` so that drake super-build can pick the system dReal if it's installed.

**Comment by soonho-tri** [comment]
@jwnimmer-tri and @tkoolen : I'll proceed and make a PR to turn it off by default. I'll also bump the hash of dReal git-submodule.

**Comment by jwnimmer-tri** [comment]
As long as dReal goes back to `ON` by default once it starts to be called by the solvers stack, that's fine with me.

**Comment by soonho-tri** [comment]
> Last I checked, ccache doesn't work with clang.

I had the same issue. For me, having the following line in `~/.ccache/ccache.conf` solves the problem.
```
run_second_cpp = true
```

> but of course only makes sense if it's relatively stable.

I agree.

**Comment by tkoolen** [comment]
Cool! I'll try that out, thanks.

**Comment by tkoolen** [comment]
Related to the `ccache` thing (but not the original issue): https://github.com/RobotLocomotion/drake/pull/3509
