### ISSUE TITLE
Mysterious Unit Test Error - Polynomial<double>("!") Failed To Throw Exception

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3852]
# The Error

```
/home/ubuntu/workspace/linux-clang-ninja-continuous-debug/drake/common/test/polynomial_test.cc:218: Failure
Expected: Polynomial<double>("!") throws an exception of type std::runtime_error.
  Actual: it throws nothing.
```

# Example CI Test Logs

* https://drake-jenkins.csail.mit.edu/job/linux-clang-ninja-continuous-debug/797/

# Prognosis

Maybe there's something stochastic in this test? @jwnimmer-tri might have experienced it months ago. Not sure.

**Comment by liangfok** [comment]
I'm going to remove the CI label since I don't think this is specific to CI. I'll also update the title.

**Comment by jwnimmer-tri** [comment]
The test case calls the `Polynomial` constructor with a string argument of `!`.  This calls `VariableNameToId`, which calls `strchr` to find the index of `!`, which is not found so returns `nullptr`, which we then compute the distance from `kNameChars ` to `nullptr`, which is random based on the linker.  The DUT should directly raise an exception on an invalid name, instead of relying on the math mapping into int-space to go out of range.

**Comment by jwnimmer-tri** [comment]
This is a fun one too, because it's not UB, just a bug -- so valgrind won't find it.

**Comment by liangfok** [comment]
Awesome. Thanks for finding the bug! What does "UB" stand for?
