### ISSUE TITLE
Order the state for a floating-base body as [quaternion; translation; angular_velocity; linear_velocity] when using kQuaternion

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#4398]
Moved the discussion from #4379. Currently the order is
```
[translation; quaternion; angular_velocity; linear_velocity]
```
This can cause confusing to users, since it puts translational part first in the generalized position, but switch the order in the generalized velocity, that the angular velocity comes first.

**Comment by naveenoid** [comment]
+1

**Comment by siyuanfeng-tri** [comment]
for euler angles, i believe the current layout is pos, rpy, posd, rpyd. 
so we are sticking to "everything rotation comes first"?

**Comment by hongkai-dai** [comment]
@siyuanfeng-tri I think only the drone people are using euler angles. @peteflorence @psiorx , do you have a preference to the ordering of the state for your drone?

**Comment by sherm1** [comment]
> for euler angles, i believe the current layout is pos, rpy, posd, rpyd. so we are sticking to "everything rotation comes first"?

At least the RPY floating joint is self-consistent between coordinates and velocities! I do think we should be consistent and always use orientation followed by translation for q and v. As a practical matter, the first step ought to be fixing the API so that user code doesn't have to be so brittle with respect to coordinate ordering. Then find and remove the brittle parts, then finally make the ordering changes hopefully without breaking anything.

**Comment by siyuanfeng-tri** [comment]
i can see this creating relatively large confusions to the current user base if we want to fix it.. (i got bitten by this a couple times already). on the other hand, i am strongly in favor of moving towards a consistent convention.

**Comment by siyuanfeng-tri** [comment]
@hongkai-dai we are as well unfortunately, i am not exactly sure for what reason. probably just history.

**Comment by siyuanfeng-tri** [comment]
i would guess most people want [pos, rotation]
