### ISSUE TITLE
Simulator<AutoDiffXd>::StepTo assertion

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#4427]
In #4422, we discovered that `Simulator<AutoDiffXd>::StepTo` fails an assertion.  We should enhance the `Simulator<AutoDiffXd>` unit testing to call StepTo, observe that the assertion trips, and then repair the code to work (and possibly adding addition tests).

**Comment by sherm1** [comment]
Also likely upgrade that assertion to a DRAKE_DEMAND.

**Comment by sherm1** [comment]
I traced this to some code in LeafSystem that looked like this:
```c++
    T min_time =
        std::numeric_limits<typename Eigen::NumTraits<T>::Real>::infinity();
```
where T was an AutoDiffScalar. The problem is that `::Real` here doesn't mean "underlying floating point type", rather it means "real part" vs. "imaginary part". Since T wasn't complex, Real is simply T. `numeric_limits` has no instantiation for that so uses its default which is to return a `T()`, garbage in this case.

Replacing `::Real` with `::Literal` (as in type of a literal for this type, say `3.14`) fixes the problem. PR coming.
