### ISSUE TITLE
Bazel Error: Linking of rule '@yaml_cpp//:lib' failed - clang: error: unsupported option '-pass-exit-codes'

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#4842]
# The Error
When building Drake using the following commands:

```
cd drake-distro
bazel build //... 
```

The build aborts with the following error:

```
ERROR: /home/liang/.cache/bazel/_bazel_liang/5441fd7edcd109c7894c36c2b6d5233a/external/yaml_cpp/BUILD:3:1: Linking of rule '@yaml_cpp//:lib' failed: linux-sandbox failed: error executing command /home/liang/.cache/bazel/_bazel_liang/5441fd7edcd109c7894c36c2b6d5233a/execroot/drake-distro-2/_bin/linux-sandbox ... (remaining 18 argument(s) skipped).
clang: error: unsupported option '-pass-exit-codes'
```

**Comment by david-german-tri** [comment]
Conclusion from Slack:

We believe that the first time @liangfok ran a Bazel command in this workspace, the `CC` or `CXX` environment variable was set to Clang.  As a result, Bazel autodetection selected the Clang compiler, and cached that choice.  However, the default `bazel.rc` was still setting GCC-specific flags, leading to the following error.  The fix is to `bazel clean`, sanity check your environment variables, and then proceed with `bazel build`.

This class of problem will be eliminated by #4772, which disables autodetection.
