### ISSUE TITLE
Unable to View Body Frames in Drake Visualizer

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#5085]
# Problem Definition

We are currently unable to view body frames using Drake Visualizer, as shown below:

![unable_to_view_body_frame](https://cloud.githubusercontent.com/assets/1388098/22703905/c0453fac-ed33-11e6-9431-a04e8f4fe0e3.png)

In the [past](https://github.com/RobotLocomotion/drake/issues/1714#issuecomment-193809869), we were able to view them, as shown below (the screenshot was taken in 2016/03):

![able_to_view_body_frame](https://cloud.githubusercontent.com/assets/1388098/22703752/37f504e8-ed33-11e6-8748-244e3357c965.png)

It would be nice to restore that functionality.

**Comment by liangfok** [comment]
@patmarion I assigned this to you in the hopes that you would know what happened. Please free to re-assign if you don't have time to restore this functionality.

**Comment by patmarion** [comment]
frame visualization was removed with this PR:  https://github.com/RobotLocomotion/director/pull/362

it was removed because there was a slowdown associated with drawing 1000s of frames at high rate.  the feature could be added back and implemented in a way to avoid the slowdown.  I'd be happy to advise if you want to work on it.

**Comment by liangfok** [comment]
@patmarion Thanks for the quick response! This feature is not urgently needed right now. I'll close this issue and re-open it once it's urgently needed, at which time we'll probably come looking for your advice.
