### ISSUE TITLE
support friction coefficient in urdf/sdf parsers

### ISSUE THREAD

**Issue by JavadHasaneini** [RobotLocomotion/drake#57]
How can I change the friction coefficient between the ground and the object in floating base models described by a urdf file?

**Comment by pmeruva** [comment]
![image](https://cloud.githubusercontent.com/assets/14628305/12246208/2e16049c-b87b-11e5-89a7-fad8ec794386.png)

![image](https://cloud.githubusercontent.com/assets/14628305/12246213/3735baea-b87b-11e5-83c0-4a5f09b84ba4.png)

![image](https://cloud.githubusercontent.com/assets/14628305/12246221/40796958-b87b-11e5-853e-0d9d3ef30d22.png)

**Comment by RussTedrake** [comment]
i don't see anything about mu in your xacro block?  

for reference, the gazebo/etc mu1 and mu2 ideas are documented here: http://gazebosim.org/tutorials?tut=friction

i much prefer twan's suggestion, but want to make sure we understand how it would play out.
we already have a materials tag, which is currently only used for visual elements.  we would be adding it for collision elements now, too.  
then there would be a new tag for friction which would take a pair of materials and assign mu.  (i don't actually see the immediate value of mu2, especially since the description seems coordinate dependent in an odd way, but we could support that if/when it becomes important).  
and we would probably want to be able to set a default mu for material pairs which are not specified.
what exactly should those tags look like and how cumbersome is it going to be to implement them for any new urdf?

**Comment by pmeruva** [comment]
In the xacro block, the Mu is represented as "friction" in the joint properties line.

I will look into what it would take to set default mu for material pairs and post it back on this issue.

**Comment by RussTedrake** [comment]
are you sure?  friction in the joint is different than coefficient of friction for contact (which is a property of the body)

**Comment by pmeruva** [comment]
Oh, my mistake, the snippet in this case is incorrect. However, I do believe that you can set the "friction" parameter as a material property within a xacro block.

**Comment by pmeruva** [comment]
Oh, my mistake, the snippet in this case is incorrect. However, I do believe that you can set the "friction" parameter as a material property within a xacro block.

Also, according to the ROS wiki, you can set default values for parameters in a Macro Xacro block using something that looks like the following line:

**Comment by pmeruva** [comment]
A snippet of XML URDF code that may work:

<link name="base_link">
     <visual>
       <geometry>
         <cylinder length="0.6" radius="0.2"/>
       </geometry>
       <material name="blue">
         <color rgba="0 0 .8 1"/>
       </material>
     </visual>
     <collision>
       <geometry>
         <cylinder length="0.6" radius="0.2"/>
       </geometry>
     </collision>
     <contact_coefficients>
       <mu1=“0.5”/>
       <mu2=“0.5”/>
       <kp=“0.5”/>
       <kd=“0.5”/>
     </contact_coefficients>
   </link>

**Comment by amcastro-tri** [comment]
Late to the discussion. Thank you @RussTedrake for adding me here. With @sherm1 we've been talking about this. We actually are planning to implement a "PhysicalMaterial" (in contrast to a material for visualization, which right now is only a color) class and every collision object would be instantiated with a material. There are composition rules to obtain the friction between a pair of objects given their individual material properties. A "MaterialsLibrary" would then help organize a collection of different common materials we'd like to model (aluminum, rubber, wood, etc.).

**Comment by amcastro-tri** [comment]
We do currently provide support for parsing friction coefficients from both URDF and SDF with `drake::multibody::Parser`. The user specifies a friction coefficient for each geometry separately. Then MBP will combine them according to the rule documented [here](https://github.com/RobotLocomotion/drake/blob/784f5a294fb5295e964aa70228f1445853fffb41/multibody/plant/coulomb_friction.h#L139).
