### ISSUE TITLE
No Default Branches Specified in On-Ramp RoadGeometry

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#5702]
I first noticed this when trying to run a `MaliputRailcar` on an on-ramp `RoadGeometry` created by `MonolaneOnrampMerge` in #5699. It wouldn't proceed across lane boundaries because no default branch was specified. I had to modify the `MaliputRailcar` to instead select the first "ongoing" branch.

I'm not sure if the above is actually a defect. Maybe it can simply be documented? (Or is it already documented and I simply missed it?)

**Comment by jadecastro** [comment]
I noticed this too when using `MonolaneOnrampMerge` to build a piecewise polynomial using `RoadPath`. I couldn't seem to obtain an ongoing lane from both the `onramp1` and `pre5` lanes.  I had tried combinations of using `MakeGroup` and adding a new branch point with some difficulty.  At some point I was getting errors to the effect of the fact that the lanes I was attempting to specify were not confluent, which is true, since I created one of those against the intended direction of travel.

@maddog-tri - perhaps you could provide some guidance?

**Comment by jadecastro** [comment]
FTR, this is the code in question: https://github.com/RobotLocomotion/drake/blob/master/drake/automotive/monolane_onramp_merge.cc

**Comment by jadecastro** [comment]
Update: Looking back on the code and the default output produced above, I think the answer to the original question is that yes- we should include the default branch in that code. 

> At some point I was getting errors to the effect of the fact that the lanes I was attempting to specify were not confluent, which is true, since I created one of those against the intended direction of travel.

I see now that the reason for this might have been a silly mistake on relying on the graphic in #5169 that isn't in sync with the code. I will update that graphic and fix the branch point problem in a separate PR.
