### ISSUE TITLE
LCM and ROS systems should appear in doxygen groups

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#6355]
http://drake.mit.edu/doxygen_cxx/group__systems.html

I would like to see a subgroup for "Message Passing" that contains the leaf systems in 
https://github.com/RobotLocomotion/drake/tree/159b31408998aea34299913843d12f49e81e3d45/drake/systems/lcm

and (if it makes sense)
https://github.com/RobotLocomotion/drake/tree/159b31408998aea34299913843d12f49e81e3d45/ros/drake_ros_systems/src

**Comment by liangfok** [comment]
I can add the LCM systems to a "Message passing" subgroup but cannot add the ROS systems because Doxygen only scans the source code in `drake-distro/drake/`:

https://github.com/RobotLocomotion/drake/blob/f71c8a52dcdb48664a7828632789c8633bbdb262/drake/doc/doxygen.py#L34

@jwnimmer-tri, can `doxygen.py` be modified to also scan `drake-distro/ros/`?

**Comment by jwnimmer-tri** [comment]
The configuration file is at https://github.com/RobotLocomotion/drake/blob/master/drake/doc/Doxyfile_CXX.in.

**Comment by liangfok** [comment]
Thanks, I modified the configuration file to include `drake-distro/ros` in #6356.
