### ISSUE TITLE
pydrake_mathematical_program_ipopt_solver_test fails when NO_IPOPT=ON

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#6500]
my .bazelrc defines 
```
build --define=NO_IPOPT=ON
test --define=NO_IPOPT=ON
```
and I see
```
//drake/bindings:pydrake_mathematical_program_ipopt_solver_test          FAILED 
```

**Comment by jwnimmer-tri** [comment]
Setting `--define=NO_IPOPT=ON` is currently not a supported configuration (and even moreso for running all tests).
- https://github.com/RobotLocomotion/drake/blob/60b5ed9724428e968a3b4029221cd1e5261af22a/tools/BUILD#L302-L309
- http://drake.mit.edu/bazel.html#proprietary-solvers

I'll see next week if there is a reasonable quick fix, otherwise will backlog this.

What's the reason for turning off IPOPT?  Perhaps its slow build?  We should be using a pre-compiled IPOPT anyway -- I'll open an issue on that next week.

**Comment by RussTedrake** [comment]
not just a slow build, but ipopt was building everytime i flipped between console bazel commands and bazel commands from clion (some argument was different which retriggered the build every time).  agreed that precompiled ipopt should resolve that problem.

**Comment by RussTedrake** [comment]
n.b. -- all other tests pass when this option is set.
