### ISSUE TITLE
Provide a cleaner way to symbolic-substitute with vectors

### ISSUE THREAD

**Issue by soonho-tri** [RobotLocomotion/drake#6925]
Feature requested by @RussTedrake in #6921.

For the following example:
```c++
symbolic::Substitution sub;
...
for (int j = 0; j < num_states(); j++) {
    sub.emplace(inspector->discrete_state(0)[j], state(i)[j]);
}
```
we want to rewrite it without a loop:
```c++
sub.emplace(inspector->discrete_state(0), state(i));
```
or
```c++
Extend(sub, inspector->discrete_state(0), state(i));
```

**Comment by jwnimmer-tri** [comment]
I found four possible call sites for this sugar:

- systems/analysis/region_of_attraction.cc: would use this as-is
- solvers/constraint: could use this, but only if emplace excludes substitutions that are no-ops
- systems/primitives/symbolic_vector_system: could use this, but anyway needs to loop to collect all variables into a set
- geometry/optimization/test/graph_of_convex_sets_test.cc: could use this, but only has two elements to hard-coding is not a burden

We can't use a class member function, because `Substitution` is an STL container, not one of our own types.  I don't think the mental burden of knowing about a free function sugar is worth the cost of compacting these loops.

Better would be to use something like Ranges, where we add a _range_ of pairs to the substitution, and that we can form ranges by a zip_view over the two lists.

For now, "won't fix".
