### ISSUE TITLE
LeggedRobotPlanningProblem

### ISSUE THREAD

**Issue by manuelli** [RobotLocomotion/drake#701]
Attemps to reference the field 'constraints' in obj.support_struct(i) which is non-existent. Maybe it should be changed to obj.constraint_struct.constraint. Could @avalenzu take a look?

-Lucas

Should comment out addSupportConstraintsToPlanner on line 306. Should also change line 334 to

prog = prog.addCost(QuadraticConstraint(-inf,inf,Q,-Q*reshape(q_nom,[],1)),prog.q_inds(:));

there was a minus sign missing in front of -Q*reshape.

The matlab error corresponding to the first problem listed above.

Reference to non-existent field 'constraints'.

Error in LeggedRobotPlanningProblem/addSupportConstraintsToPlanner (line 412)
        if ~isempty(obj.support_struct(i).constraints)

Error in LeggedRobotPlanningProblem/generateQuasiStaticPlanner (line 304)
      prog = obj.addSupportConstraintsToPlanner(prog);

**Comment by avalenzu** [comment]
Sorry about that. We ought to have a test for `LeggedRobotPlanningProblem` in drake. We didn't catch this in DRC because we're adding the quasistatic constraint directly.

Actually, I think that call to `addSupportConstraintsToPlanner` is unnecessary. Can you try commenting out line 304 in `generateQuasiStaticPlanner`?

**Comment by manuelli** [comment]
Yes I figured that out yesterday. Commenting out that line seems to work.
