### ISSUE TITLE
Use system nlopt

### ISSUE THREAD

**Issue by soonho-tri** [RobotLocomotion/drake#7335]
For now, we're building [nlopt](https://nlopt.readthedocs.io/en/latest) in bazel build. I'm wondering if we can switch to use the one in a system. FYI, both of macOS (via homebrew) and Xenial provide the latest version of nlopt, `2.4.2`.

 - macOS (homebrew): https://github.com/Homebrew/homebrew-core/commits/master/Formula/nlopt.rb
 - Ubuntu Xenial https://packages.ubuntu.com/source/xenial/nlopt

/cc @jwnimmer-tri , @stonier.

**Comment by soonho-tri** [comment]
My motivation is that dReal has a plan to use (system's) `nlopt` and I'd like to avoid any possible conflicts in Drake (between the system nlopt and locally-built nlopt).

Also `nlopt` is under LGPL which requires dynamic linking. I think relying on the system one can prevent possible static linking (or not?)

**Comment by soonho-tri** [comment]
@clalancette , could you check if this change can cause a problem (vs. ROS)? @jwnimmer-tri shared  a document, `Dependencies Drake vs ROS (Xenial)` with me, and it seems that we won't have a problem.

**Comment by clalancette** [comment]
@soonho-tri I did a bit of investigating here.  You are absolutely correct; Xenial does have nlopt 2.4.2, so that will be compatible with what is in Homebrew (it also happens to be the latest official release from nlopt).  2.4.2 is older than what drake is currently using, but from a brief look of the changes since 2.4.2, none of them seem to be API-breaking, so that will be OK as well.  As far as linking with ROS, I don't forsee any trouble; a bunch of other ROS packages depend on the system version of nlopt.  So it seems like it would be totally fine to change to a system version of nlopt.  I hope that is helpful.

**Comment by soonho-tri** [comment]
@clalancette , thanks a lot for the detailed analysis. I'll open a PR making the transition.
