### ISSUE TITLE
Fail hard if the wrong Eigen is found

### ISSUE THREAD

**Issue by stonier** [RobotLocomotion/drake#7382]
That is, when doing find_package(drake) or adding it as an external in a CMake project.

**Comment by jamiesnape** [comment]
CMake will already fail hard if it finds an incompatible version. Where are you seeing problems?

**Comment by jwnimmer-tri** [comment]
From timing, I suspect it was related to RobotLocomotion/drake#7378.  (I don't have any more details, though.)

**Comment by jamiesnape** [comment]
So do we 3.3.3 or 3.3.4? If we need 3.3.4, then we need to tell CMake. Otherwise #7378 should be entirely redundant unless you are doing something that you shouldn't be with CMake.

**Comment by jamiesnape** [comment]
@EricCousineau-TRI do you have any background since you opened that PR?

**Comment by jamiesnape** [comment]
(And if you happen to be calling `find_package(Eigen CONFIG REQUIRED)` independently and not specifying a version, then clearly you are not going to get a hard fail. The solution there is to correctly specify your requirements.)

**Comment by jwnimmer-tri** [comment]
To my knowledge, Drake needs only 3.3.3.

I was happy to accept the "If we have 3.3.4, then disable the traits thing that is now provided upstream" portion (`common/eigen_autodiff_limits.h`), because it enables off-label use of Drake with newer Eigen, and would be correct when we add support for Ubuntu 18.04 in the future, for example.

As to why we are improving the diagnostic with Eigen < 3.3.3 (`common/autodiff.h`), I don't know.  I agree it seems odd given that CMake should already have complained by then, but seemed like a reasonable second-line fail-fast.  (In retrospect, we could probably improve the `static_assert`'s comment though, hinting to users that their CMakeLists.txt files are broken somehow.)

**Comment by jamiesnape** [comment]
This looks suspicious, though: https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/eigen/eigen-create-cps.py#L14

**Comment by jamiesnape** [comment]
I think maybe it is the definition of "incompatible version" then. The changes in #7396 fix that. As much as people thing CMake looks around their whole system for literally any version of a package, that is not how it works, so issues like #7378 should probably be brought to our attention to fix.

**Comment by jwnimmer-tri** [comment]
Agreed.

**Comment by jwnimmer-tri** [comment]
It seems to me like nothing is left to do here.
