### ISSUE TITLE
How to use external packages?

### ISSUE THREAD

**Issue by yurivict** [RobotLocomotion/drake#7665]
I am trying to port to FreeBSD, but it seems like you expect binary packages to be prepared for dependencies:
```
    if os_result.is_macos:
        archive = "dv-0.1.0-173-g6e49220-qt-5.9.1-vtk-8.0.1-mac-x86_64.tar.gz"
        sha256 = "65b78914327c82bb8fd7cf2182dedc2a45edeafc44fc229415528ee2180bf9a4"  # noqa
    elif os_result.ubuntu_release == "16.04":
        archive = "dv-0.1.0-173-g6e49220-qt-5.5.1-vtk-8.0.1-xenial-x86_64.tar.gz"  # noqa
        sha256 = "57ebe3cef758b42bdc1affb50e371a1e5224e73e3c2ebe25dcbba7697b66d24d"  # noqa
    else:
        fail("Operating system is NOT supported", attr = os_result)
```

This assumes that it has to be a) pre-built and available b) downloaded here.
What is the source of 'dv'?

There are packages for dependencies. You can't just install every dependency with every package - you will run out of space.

Same for vtk/eigen/etc. How do I use the pre-installed packages?

**Comment by jwnimmer-tri** [comment]
> I am trying to port to FreeBSD, but it seems like you expect binary packages to be prepared for dependencies ...

Yes, for some few dependencies, we download prebuilts.  (Most dependencies come from the host OS or are built from source.)

Our list of supported platforms is shown at http://drake.mit.edu/developers.html#supported-configurations.

> What is the source of 'dv'?

The term `dv` is short for "drake-visualizer", which comes from https://github.com/RobotLocomotion/director/.

> Same for vtk/eigen/etc. How do I use the pre-installed packages?

VTK is the other major pre-built.  The `is_macos` cases in https://github.com/RobotLocomotion/drake/tree/master/tools/workspace/vtk would be similar to what you'd need to use a different VTK, without downloading anything.

Eigen by Default we actually download as source.  If you'd like to change e.g. what Eigen is used, that's governed by https://github.com/RobotLocomotion/drake/tree/master/tools/workspace/eigen.  You could try changing those rules to look more like, e.g. https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/glib, which is the rule for using the host OS glib.

That all being said, since we don't officially support FreeBSD, I am going to close this out for the moment.
