### ISSUE TITLE
Files in https://launchpad.net/~dreal/+archive/... have gone missing

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#8359]
The file https://launchpad.net/~dreal/+archive/ubuntu/dreal/+files/libibex-dev_2.6.3.20171215122721.git2275df8f465a9db6a42d497ca322011ff2c6f8f7~16.04_amd64.deb, which was cited by `install_prereqs.sh` in Drake for a while on master, no longer exists.  It seems that we still have them archived at https://drake-apt.csail.mit.edu/pool/main/libi/libibex-dev/libibex-dev_2.6.3.20171215122721.git2275df8f465a9db6a42d497ca322011ff2c6f8f7~16.04_amd64.deb so at least uses can manually install them.

Ideally, we'd keep those files available indefinitely so users on older tags or bisecting could still automatically compile.  Failing that, I guess we can close this issue and point people here for the work-around FAQ.

**Comment by soonho-tri** [comment]
It's because [launchpad.net](https://launchpad.net/) does not keep old `.deb` files. We've moved to [drake-apt.csail.mit.edu](https://drake-apt.csail.mit.edu) where we can keep all versions. So we are not going to make a new problem.

If one wants to download old versions of dReal or Ibex. Please find them at the following URLs:
 - https://bintray.com/dreal/dreal/dreal
 - https://bintray.com/dreal/ibex/ibex
