### ISSUE TITLE
DrakeVisualizer publishes a NaN pose at rgbd_camera_publish_lcm_test

### ISSUE THREAD

**Issue by kunimatsu-tri** [RobotLocomotion/drake#8368]
This is how to reproduce:
```
$ cd systems/sensors
$ bazel run :rgbd_camera_publish_lcm_test
```

and this is the result I got from `drake-lcm-spy`:
![image](https://user-images.githubusercontent.com/21087695/37424183-4a2a4300-2796-11e8-8af9-0cfe76ae276f.png)

Relates: #8345

**Comment by mitiguy** [comment]
Overview: The test rgbd_camera_publish_lcm_test is defective.
It has been disabled.  If you have objections, let me know.

History: There is a new rigorous RotationMatrix class.
The functions rotmat2quat and quat2rotmat are now deprecated.

Problem 1:
Due to a defect in the test rgbd_camera_publish_lcm_test, 
there were problems when rotmat2quat was deprecated.  
It was possible to isolate this problem to a single call to rotmat2quat on
line 69 of the file /drake/multibody/rigid_body_plant/viewer_draw_translator.cc.
The following code was initially added to isolate this problem.
    // TODO(mitiguy) when issue #8368 is resolved, change the next line so it
    // instead uses the method drake::math::RotationMatrix::ToQuaternion().
    // Suppress deprecation warning for rotmat2quatOld.
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wdeprecated-declarations"
    auto quat = drake::math::rotmat2quatOld(transform.linear());
    #pragma GCC diagnostic pop  // pop -Wdeprecated-declarations

Problem 2: 
However, when quat2rotmat was also deprecated, the test
rgbd_camera_publish_lcm_test again failed CI.  
Unfortunately, this failure was not isolatable 
to a single call of quat2rotmat.  

Helpful detective hint:
One consistent indication of the defect 
(in both rotmat2quat and quat2rotmat) 
is that elements of a quaternion 
are being assigned NANs.

Note: The following comment now appears in appropriate BUILD.bazel file.
   # TODO(mitiguy) Issue #8368: Test rgbd_camera_publish_lcm_test in the
    # BUILD.bazel file in directory drake/systems/sensors cannot be run anymore
    # due to the new RotationMatrix class which insists on being a proper
    # orthogonal rotation matrix.  This test produces a quaternion with NANs
    # which causes the RotationMatrix class to throw an exception in debug
    # builds. This test is labeled with tags = "manual" so CI does not run it.
    # This test is defective and should never have passed earlier code review.

**Comment by sherm1** [comment]
Seems like a good test -- any hope for fixing it soon, @kunimatsu-tri ?

**Comment by jwnimmer-tri** [comment]
For the record:
- Relates #8412.
- Use `-c dbg` to reproduce this.  It is a Debug-only check that's failing.

**Comment by kunimatsu-tri** [comment]
I'm working on other urgent things right now. Once I finish them, I'll work on solving this hopefully sometime this week.

**Comment by kunimatsu-tri** [comment]
It turned out that the bug was coming from wrong SDF modes which don't have `inertia` property.

![image](https://user-images.githubusercontent.com/21087695/41194443-574a2cb6-6be9-11e8-884a-01f7719e5e5a.png)
