### ISSUE TITLE
styleguide: Instructions for updating via rebase for upstream changes are unclear / inconsistent with git log

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#8638]
At present, the `RobotLocomotion/styleguide` instructions for updating state that a PR should be submitted by rebasing your changes on `google/gh-pages`:
https://github.com/RobotLocomotion/styleguide/tree/7e286c89ccd69be2d35aa8e9879a89cca012d812#pulling-upstream-changes

However, when a PR is submitted as a rebase, the diff is against the `git merge-base` of `RobotLocomotion/gh-pages` and the PR, which will then show *both* the changes from `upstream` and *all* changes for Drake.

From a Slack conversation:

> I'm a tad confused by the `gh-pages` merge procedure for `RobotLocomotion/styleguide`.
> 
> From looking at our PR history, it seems that this procedure *may* have been exercised in https://github.com/RobotLocomotion/styleguide/pull/4
> 
> However, looking at it more closely, the following seems to be apparent:
> 
> - Upstream `google/gh-pages` was merged into `RobotLocomotion/gh-pages` - it was not a rebase
> - When merged, it was a squash merge: When I now inspect the history, there are two things: (1) we have *not* actually incorporated upstream commits (because they were squashed), so now we lose out on upstream resolutions that we've already fought, and (2) we are not *rebased* on upstream commits.
> 
> That being said, it seems that the instructions are a tad inconsistent: they should either (a) state that we are *not* going to be on upstream commits, and will have our own baseline, or (b) we should stick to faithfully rebasing, in which case, the instructions need better clarification.
> 
> For (b), I have experience with this workflow `pybind11`, and can reflect a robust procedure.
> However, (a) would be much simpler.

To add to (b), it would be much simpler if the Review were done in such a way that you only review the changes from `upstream` and the changes to the *existing* Drake updates (a direct diff, not a merge-base diff).
See the following [Gitter conversation](https://gitter.im/Reviewable/Reviewable?at=5ad8c8c22b9dfdbc3aa9eddf) for more example, and what a workaround could be -- e.g. first submitting the changes based on `RobotLocomotion/gh-pages`, e.g. via `git checkout ${actual_rebase} -- :/` or whatever, reviewing, making changes, and then making a follow-up PR which actually has the rebase (to maintain the prior review PR in it's entirety).

Ran into this when figuring out how to best incorporate @m-chaturvedi's upstream changes in his PR: https://github.com/RobotLocomotion/styleguide/pull/6

**Comment by jwnimmer-tri** [comment]
Okay, I have finally reviewed and read everything relevant.  I agree that we should choose _only_ to either merge from google **xor** rebase on google, and always do the same choice, and never use squashes.  Thus, whatever we choose, we should change Settings tab in GH to enforce it.

My intuition is that the merge workflow matches what we want -- google has their baseline (with many commits), we have our patches (as many commits), and they both independently evolve over time.
@ggould-tri do you have thoughts on why you suggested rebase?

In any case, once we choose an answer, we will have to pin a protected branch or tag to current master (to force keeping its sha's around forever since Drake refers to them), and then we'll force-push whichever way we wanted over the erroneous squash in RobotLocomotion/styleguide#4.

**Comment by EricCousineau-TRI** [comment]
As a minor technical note, I like having a general purpose `no_prune` or `no_gc` branch, in which you can use `git merge --strategy=ours`, so you can preserve prior commits. This avoids the need to have relatively random tags if the main goal is to avoid pruning / garbage collection.

**Comment by ggould-tri** [comment]
I don't recall why I recommended rebase, but it was probably in order to minimize divergence from the Drake workflow (on the assumption that not every style guide maintainer will be a git expert).

I agree that merge is a superior choice for this repo, and if we are confident that having different repos using different strategies is a reasonable plan then it seems conceptually correct.

**Comment by EricCousineau-TRI** [comment]
Sounds good!

**Comment by jwnimmer-tri** [comment]
Note that thanks to @EricCousineau-TRI in RobotLocomotion/styleguide#8 we have a new history for `styleguide` master that uses the merge workflow now.
