### ISSUE TITLE
Set parameters for Mosek in MathematicalProgram

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#8674]
Currently we cannot set parameters for Mosek. Unlike other solvers, whose parameters can be set through `MathematicalProgram::SetSolverOption(SolverId solver_id, const std::string& parameter, double value)`, Mosek's parameter is defined as enum in `Mosek.h`, not as a string.

One non-ideal solution to this problem is to add a function `MathematicalProgram::SetSolverOption(SolverId solver_id, int parameter, double value)`.

@jwnimmer-tri what do you think?

**Comment by jwnimmer-tri** [comment]
Would it be confusing to users to have a string key whose name is identical to the enum item?

```c++
prog.SetSolverOption(MosekSolver::id(), "MSK_DPAR_INTPNT_QO_TOL_REL_GAP", 1.0e-10);
```

I don't think finding string typos at compile-time is a big enough hazard to worry about, but if you wanted compile-time checking, then we could also offer
```c++
std::string to_string(MSKdparam_enum);  // A helper function in mosek_solver.h
prog.SetSolverOption(MosekSolver::id(), to_string(MSK_DPAR_INTPNT_QO_TOL_REL_GAP), 1.0e-10);
```
backed by a dictionary that we'd need anyway to map from names to the integral values to pass to `MSK_putdouparam`.

**Comment by sherm1** [comment]
Since the string argument is just as ugly as the enum, is there any advantage to using the string at all?

**Comment by jwnimmer-tri** [comment]
@sherm1 The string key keeps the "set option _string_ to value _double_ on solver _id_" as a uniform API no matter which back-end is in use (http://drake.mit.edu/doxygen_cxx/classdrake_1_1solvers_1_1_mathematical_program.html#a77b58f1d09a3aec5918813ba163c1098).

@hongkai-dai Even listing out all 69 options manually into a `map<string, int>` would not be very hard, and then both `mosek_solver.cc` and `to_string` would use that map to process options.  It would also be easy to have a BUILD rule to autogenerate the map by scanning the mosek header.  (We could easily have a compile-time error message remind us to update the map, since MOSEK provides the count of parameters as a compile-time constant.)

**Comment by hongkai-dai** [comment]
@jwnimmer-tri thanks for pointing out the solution! Do we have an example in drake, that writes a BUILD rule to auto generate a map?

**Comment by jwnimmer-tri** [comment]
If you can write a small python program that takes on the command-line an input and output filename argument, where `mosek.h` would normally be passed in as input, and this program emits a C++ header as output (you can test this yourself standalone), then I can quickly help you integrate it into the build.

If you look in `tools/workspace/godotengine` for example the `update_version` (or similar) stuff would be similar to this.
