### ISSUE TITLE
Pydrake support auto-completion

### ISSUE THREAD

**Issue by CatchMeFastFat** [RobotLocomotion/drake#8832]
I want to use editor linter and auto-complete `pylint/jedi `features with python. It was working well for C++ with rtags. 
```
import pydrake
from pydrake.common import FindResourceOrThrow
from pydrake.multibody.rigid_body_plant import RigidBodyPlant
from pydrake.multibody.rigid_body_tree import RigidBodyTree
from pydrake.systems.analysis import Simulator
```
When I use `import pydrake` then try to use any class, autocompletion "as well as linter" doesn't detect classes only their headers.

example: `pydrake.multibody.rigid_body_plant.` doesn't suggest any completion.

Noticed from pybind11 repo. 
> pybind11 is a lightweight header-only library

Is there any way to make it grap classes names?

**Comment by EricCousineau-TRI** [comment]
This would be heavily dependent on the linter, and I think is an issue more for the autocompletion tool and not for Drake. `jedi` does seem to support parsing `c_builtin` modules, which is effectively what `pydrake` is by means of `pybind11`:
https://jedi.readthedocs.io/en/latest/docs/features.html#caveats

One thing is that `pybind11` tends to generate classes with a specific metaclass, so that may be affecting things, though it's rather hard to interpret this class:
https://jedi.readthedocs.io/en/latest/docs/features.html#not-supported

You may want to post on StackOverflow for `jedi` to get their help; there might be issues with how `jedi` parses the Python path in your project:
https://stackoverflow.com/questions/tagged/python-jedi

I will keep this open for a few more days, but close if there is no other activity on Drake, as I believe the only way you'll get valuable help is through the `jedi` community.

As an aside, autocompletion works with whatever Jupyter / IPython naturally uses.
An an example, from a fresh kernel, I can type
`from pydrake.multibo` and end up completing to
`from pydrake.multibody.rigid_body_plant`, and can then autocomplete based on
`from pydrake.multibody.rigid_body_plant import ` to something like
`from pydrake.multibody.rigid_body_plant import RigidBodyPlant`.

**Comment by CatchMeFastFat** [comment]
In jupyter I excuted `%config IPCompleter.greedy=True` ,'import pydrake.all' and 'import os'.

`os.` works well, but `pydrake.` only gives `pydrake.install` as a completion in `/home/drake/build/install/drake/lib/python2.7/site-packages/pydrake/util/deprecation.pyc in install(cls, name, handler)`

I want to use this method "similar to C++":

```
import pydrake.all
tree = pydrake.multibody.rigid_body_plant.
```
to 

```
import pydrake.all
tree = pydrake.multibody.rigid_body_plant.RigidBodyPlant()
```

BTW: in `lib/python2.7/site-packages/pydrake/all.py`
> To see example usages, please see `doc/python_bindings.rst`.

I can't find this file!Is it http://drake.mit.edu/python_bindings.html ?
