### ISSUE TITLE
Bindings shouldn't get added to build_components.bzl

### ISSUE THREAD

**Issue by avalenzu** [RobotLocomotion/drake#9107]
Currently running `build_components_refresh.py` adds new lines for `//bindings/pydrake/*`. It shouldn't (or so I'm told).

**Comment by EricCousineau-TRI** [comment]
Shortly after we discussed this, I realized that maybe it should be there, since these headers are available to downstream users in Bazel-land; however, perhaps this shouldn't be merged until https://github.com/RobotLocomotion/drake-shambhala/pull/98 is resolved and merged in.

Either way, I don't think it's harmful either way.

**Comment by jwnimmer-tri** [comment]
This is already fixed https://github.com/RobotLocomotion/drake/blob/883d558690c4c1e86a009177ce19dfccd02fac5a/tools/install/libdrake/build_components_refresh.py#L39 (by excluding bindings entirely).  If we want to provide bindings/pydrake utilities helpers to CMake downstreams, that should be a separate issue (and probably not worth worrying about yet.)
