### ISSUE TITLE
make common drake visualizer scripts available always?

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#9608]
As it stands right now, only the most advanced users can figure out how to launch drake_visualizer with the magical invocation to see what we typically see.  Is there any harm of promoting
```
cmd "0.drake_visualizer" {
    exec = "${DRAKE_WORKSPACE}/bazel-bin/tools/drake_visualizer \
        --script ${DRAKE_WORKSPACE}/multibody/rigid_body_plant/visualization/contact_viz.py \
        --script ${DRAKE_WORKSPACE}/multibody/rigid_body_plant/visualization/show_time.py \
        --script ${DRAKE_WORKSPACE}/multibody/rigid_body_plant/visualization/show_frames.py";
    host = "localhost";
}
```
so that it happens always?  (should be a simple addition to drake_visualizer.py?)

@jwnimmer-tri ?  @EricCousineau-TRI ?  @sammy-tri ?

**Comment by EricCousineau-TRI** [comment]
I have soft preference to still make these modules / this functionality opt-in, rather than always-on. However, the way that we do that can change.

In Anzu, we expose all of the general functionality via `${PYTHONPATH}`, so that any script can import them. We still refer to script paths, but we could potentially get to a point to where each application has its own initialization script in the same directory as the PMD, so that the launch would look like:
```
cmd "0.drake_visualizer" {
    exec = "${DRAKE_WORKSPACE}/bazel-bin/tools/drake_visualizer \
        --script ./drake_viz_custom_app.py";
    host = "localhost";
}
```

That way you maintain explicit-ness, but there's less copy-pasta.

**Comment by RussTedrake** [comment]
The contact arrows will do nothing unless someone is actively publishing contact results.  I would argue that if someone is publishing it, then it should be shown by default (eg on by default at the visualizer side).

**Comment by RussTedrake** [comment]
Also just became aware/reminded of 
```
-script systems/sensors/visualization/show_images.py
```
Searching suggests that these four are all of the relevant in-tree scripts.
