### ISSUE TITLE
[sensors] ColorPalette untested and apparently unused

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#9628]
There are no unit tests for the `ColorPalette` class. However, a quick grep of the project suggests that it's not being used at all anymore (with the removal of attic).

Propose:

- Deprecate the class (after searching Anzu)
- Move the color definition (`Color`, `ColorI`, `ColorD`) into its own file.
    - Deprecate the `color_palette.h` file but have it include the new header with the `Color*` classes so it's still a viable path to those structs.

**Comment by jwnimmer-tri** [comment]
I can confirm that in 2023 is still unused in Drake and Anzu, and still not unit tested.

> Move the color definition (Color, ColorI, ColorD) into its own file. 

I don't like having both `Color` and `Rgba`.  Possibly we could deprecate `LabelFromColor` and `GetColorIFromLabel` and `GetColorDFromLabel` instead, since those should really be internal implementation details of any given render engine.

**Comment by jwnimmer-tri** [comment]
This completely clogs up any useful package topology.  I'll fix it today.
