### ISSUE TITLE
Calling path from solveLCPmex

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#965]
Quick idea:  you could cut out the call to mexcallmatlab if you did a dlopen and called the mexFunction for the path matlab libs directly.  It might be a way to get a little more performance out.  See https://github.com/RobotLocomotion/drake/blob/master/util/drakeDebugMex.cpp 
For a very similar example.

**Comment by RussTedrake** [comment]
Also..  Although it wouldn't get rid of the matlab lib dependencies, it would getvrid of the matlab runtime dependecy, so we'd be closer to being able to simulate lcps from a standalone app.

**Comment by psiorx** [comment]
Would this work in windows?

**Comment by RussTedrake** [comment]
no, but only because the path mex libraries don’t work on windows.

**Comment by psiorx** [comment]
Played around with this idea a bit today.  It's close to working but I ran into a few snags.

The ```lcppath.mex*``` files expect a sparse matrix representation of ```M```.  This is normally handled by the matlab wrapper ```pathlcp.m``` which simply calls ```sparse()``` on the matrix before handing it down.  

Doing this directly in mex is a little bit hairier. 

I've written a general purpose ```eigen2mexsparse``` utility function which does this but MATLAB is complaining at runtime with this obscure error:  ```MATLAB:err_sparse_64bit_obsolete```

Digging a little deeper, it seems that our mex files are being compiled against the 32-bit mex API.  Referencing back to the release notes of R2006b, they say that in order to enable compilation against the new 64-bit mex API, we need to compile with the ```-largeArrayDims``` flag.  

I've added this to the ```MEX_COMPILE_FLAGS``` cmake variable in ```./cmake/mex.cmake``` but the error persists.  Manually compiling the mex file from within MATLAB with the same flag seems to work.  

Any idea why the ```-largeArrayDims``` flag doesn't seem to be taking hold?

**Comment by psiorx** [comment]
I think I figured this one out.  

Our build logic is forcing 32-bit compatibility by including the ```-DMX_COMPAT_32``` flag somewhere.  Any reason why we need to keep this?

**Comment by psiorx** [comment]
I submitted a pull request to the cmake submodule which resolves this.  I tested the performance of the dlopen approach and it seems to be comparable to mexCallMATLAB since the overhead of the function call is small compared with the time the function takes.  


51.896 s  original solveLCP
32.197 s  solveLCPmex w/mexCallMATLAB
29.847 s  solveLCPmex w/dlopen 

It's going to be somewhat messy trying to pick the right platform dependent mex-file if we go this route.
