### ISSUE TITLE
bazel support for jupyter notebooks in drake

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#9650]
Can we have a version of jupyter_py.bzl (e.g. from anzu) for drake, please?

**Comment by EricCousineau-TRI** [comment]
Would love to, as I really like using it in Anzu.

The main blocker way back when was dep management on Xenial; it'd be great to use `python-jupyter`, but it only exists for Bionic.
We can do pip packaging, but then we start to open a can o' worms of dep duplication.

Will tinker with this some.

@jamiesnape Can I ask how hard it might be to provide our own custom `python-jupyter` package, or use another PPA for this?

**Comment by jamiesnape** [comment]
I doubt it would difficult.

**Comment by jwnimmer-tri** [comment]
@RussTedrake What would you like to use this for?  Are the Jupyter dependencies only at build-time, would the the installed image also have them?

Unlike Anzu, Drake's install places certain requirements on what is appropriate to depend on, or what is going to be too difficult.  Integrating a non-Ubuntu version of Juypter into Drake's installed ecosystem on Xenial might be one bridge too far, with our current tooling.

**Comment by RussTedrake** [comment]
I would like to include ipynb in /drake/examples/*/ folders.  Unlike other python files, I think it is clear that these do not need to be installed.  Not a high priority for me.

**Comment by EricCousineau-TRI** [comment]
Depending on the resolution of #9833, it may be relatively easy to incorporate Jupyter notebooks if we do platform-dependent testing, as I believe we can more easily install Jupyter on Bionic:
https://askubuntu.com/a/941745/692420

Since the code already exists in Anzu, it'd be relatively easy to port.

**Comment by jamiesnape** [comment]
I guess I missed the connection to #9833.

**Comment by hongkai-dai** [comment]
@EricCousineau-TRI I created some tutorials using ipython, in #11694. It depends on supporting jupyter notebook in Drake. Is there a plan to resolve this issue in the near future?

**Comment by EricCousineau-TRI** [comment]
In line with what Jeremy said, would generally like to wait after we drop Xenial so there doesn't need to be conditions or shims (or we don't have to vendor in Jupyter).
Would that be OK for you?

FTR, we probably won't support JupyterLab as Ubuntu Bionic doesn't seem to ship it. That's probably not a huge issue here, though.

**Comment by jwnimmer-tri** [comment]
For my part, I suspect the BUILD logic for excluding notebooks on EOL platforms would be pretty easy -- just a judicious use or two of `select()` to nerf some rules when `os == xenail || python == 2`.  We already have platform-specific rcfiles and --config things in play.  For me, the main question is how much effort the _desired_ platforms will take (i.e., the work to get python3 notebooks working in 18.04 on master).

**Comment by hongkai-dai** [comment]
> In line with what Jeremy said, would generally like to wait after we drop Xenial so there doesn't need to be conditions or shims (or we don't have to vendor in Jupyter).
Would that be OK for you?

If  Jupyter notebook only runs with Python 3 on Bionic, that would already solve my issue. I can add jupyter tutorials for MathematicalProgram. If supporting Python3 on Bionic isn't much work, then I guess we could support it? The tutorials would help solve part of the usability issue of Drake. I don't need to use JupyterLab.

**Comment by EricCousineau-TRI** [comment]
Gotcha. I briefly tried out a subset of Anzu's Jupyter notebooks, and seems OK (some regressions) when using system Jupyter, so it should be fine to have some of that come into Drake.

I'd like to see if I can resolve some of the version control issues using something like `jupytext` or whatever, so that we don't have to pay the cost of awkward review in Drake as well.
Will try to see what this looks like by end of next week - does that work for you?

**Comment by hongkai-dai** [comment]
> I'd like to see if I can resolve some of the version control issues using something like jupytext or whatever, so that we don't have to pay the cost of awkward review in Drake as well.
Will try to see what this looks like by end of next week - does that work for you?

That is awesome, thanks a lot! I just hope we don't wait until the end of the year, when we will deprecate Xenial.

**Comment by EricCousineau-TRI** [comment]
First step here will be to put my stuff in my `repro` repository, and see what's necessary for doing `jupytext`-style plugins (if practical).

If that doesn't work, then we can just commit the IPYNB files, knowing that review won't be great.

**Comment by EricCousineau-TRI** [comment]
Put stuff into `repro`, updating old spike test with a simplified version of what we have in Anzu:
https://github.com/EricCousineau-TRI/repro/blob/1f824d855b56e565a554a1b79a3caefb7123937f/bazel/jupyter_integration/README.md

Next step is to play with `jupytext` or whatevs in this workspace (probably hacking with `pip` if need be).

**Comment by EricCousineau-TRI** [comment]
@hongkai-dai What sort of timeline would like to have your tutorial land?

Just thinking on it some more, if using something like `jupytext` to make reviewing easier, we may pay a cost of not being able to preview the notebook in GitHub, or use it easily in Colab. (I haven't had a chance to dig in.)

We could just pull the trigger and eat the cost of reviewing JSON files? (since you've already reviewed it in your PR.)

Or we can look into the more Reviewable-centric approach - either before or after.

**Comment by hongkai-dai** [comment]
@EricCousineau-TRI since the PR has been sitting there for a while, I don't think it matters to wait longer for a better solution. I can wait if you think using `jupytext` will make reviewing process easier. Thanks for working on it!

**Comment by RussTedrake** [comment]
I would like to have them in place before the fall semester starts, if possible.

**Comment by EricCousineau-TRI** [comment]
Following up, [first day of classes](https://registrar.mit.edu/calendar) is 2019/09/04. Should be viable, just doing some more cleanup / simplification in Anzu.
