### ISSUE TITLE
Simulink models started for simulation remain open

### ISSUE THREAD

**Issue by KeyDamo** [RobotLocomotion/drake#978]
Models opened inside ```getModel@DrakeSystem``` when running the ```simulate@DynamicalSystem``` function remain open.  I refer specifically to this line (around 221 DrakeSystem.m):
```Matlab
new_system(mdl,'Model');
```
This is why Matlab, when closing, asks whether to save or discard systems one tested before but do not appear visible. 

It's not a very important issue, just that they remain invisible and in memory. If there is no purpose for this happening, then the possibility of it bringing problems in the future exists.

Since I have to run a lot of tests and collect a lot of data, I have a script with the following lines running after a batch of simulations:
```matlab
openModels=find_system('SearchDepth',0);
for ind=1:length(openModels)
  close_system(openModels(ind),0);
end
clear openModels ind
```

**Comment by RussTedrake** [comment]
this was a known issue ("feature"?) when it was first implemented.  but it's probably worth revisiting, because we have some better tools now.  for instance, we could add a SharedDataHandle which called close on the model after the last reference is gone.  I don't have time to fix it immediately, but thank you for putting it on the stack.
