### ISSUE TITLE
Support CSDP as the open-source SDP solver

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#9922]
[CSDP](https://github.com/coin-or/csdp/) is an open-source SDP solver in C. It uses EPL-2.0 license. @jamiesnape or @jwnimmer-tri Is this license compatible with Drake? I saw we support EPL-1.0 license in https://github.com/RobotLocomotion/drake/issues/4045.

@frankpermenter have you used CSDP before?

**Comment by hongkai-dai** [comment]
related to #3773

**Comment by hongkai-dai** [comment]
Thanks @jamiesnape .

Will add this solver while (or after) refactoring `MathematicalProgram` outlined in #9633

**Comment by hongkai-dai** [comment]
@jwnimmer-tri may I ask you to do me a favor? Could you show me if we have an example in Drake, to create the bazel build file for CSDP? I hope I can write the wrapper for CSDP in Drake before I leave for Spain next Wednesday, so that @ManuelAhumada-TRI can use it for his work.

**Comment by jwnimmer-tri** [comment]
@jamiesnape Help remind me -- with EPL code do we need to link it dynamically?  My recollection is no.

Assuming that's true, a fair guide is probably https://github.com/RobotLocomotion/drake/tree/master/tools/workspace/tinyobjloader though you'll have `glob()` for the srcs and headers since there are more than one.

**Comment by jamiesnape** [comment]
Generally not, http://www.eclipse.org/legal/eplfaq.php#LINK.
